#pragma once

#include <cstdint>

enum class GuildId : int32_t {
    GUILD_OF_ELEMENTS = 0,
    GUILD_OF_SELF = 1,
    GUILD_OF_AIR = 2,
    GUILD_OF_EARTH = 3,
    GUILD_OF_FIRE = 4,
    GUILD_OF_WATER = 5,
    GUILD_OF_BODY = 6,
    GUILD_OF_MIND = 7,
    GUILD_OF_SPIRIT = 8,
    GUILD_OF_LIGHT = 9,
    GUILD_OF_DARK = 10,

    GUILD_FIRST = GUILD_OF_ELEMENTS,
    GUILD_LAST = GUILD_OF_DARK
};
using enum GuildId;

enum class HouseSoundType : uint32_t {
    HOUSE_SOUND_GENERAL_GREETING = 1,
    HOUSE_SOUND_GENERAL_NOT_ENOUGH_GOLD = 2,

    HOUSE_SOUND_MAGIC_GUILD_MEMBERS_ONLY = 3,
    HOUSE_SOUND_SHOP_GOODBYE_RUDE = 3,
    HOUSE_SOUND_SHOP_GOODBYE_POLITE = 4,
    HOUSE_SOUND_ALCHEMY_SHOP_GOODBYE_REGULAR = 3,
    HOUSE_SOUND_ALCHEMY_SHOP_GOODBYE_BOUGHT = 4,
    HOUSE_SOUND_TEMPLE_GOODBYE = 3,
    HOUSE_SOUND_BANK_GOODBYE = 3,
    HOUSE_SOUND_TAVERN_RENT_ROOM = 2,
    HOUSE_SOUND_TAVERN_BUY_FOOD = 3,
    HOUSE_SOUND_TAVERN_NOT_ENOUGH_GOLD = 4,
    HOUSE_SOUND_TRAINING_TRAIN = 2,
    HOUSE_SOUND_TRAINING_CANT_TRAIN = 3,
    HOUSE_SOUND_TRAINING_NOT_ENOUGH_GOLD = 4,
    HOUSE_SOUND_TRANSPORT_TRAVEL = 2,
    HOUSE_SOUND_TRANSPORT_NOT_ENOUGH_GOLD = 3
};
using enum HouseSoundType;
