var searchData=
[
  ['iaudiodatasource_0',['IAudioDataSource',['../classIAudioDataSource.html',1,'']]],
  ['iaudiosample_1',['IAudioSample',['../classIAudioSample.html',1,'']]],
  ['iaudiotrack_2',['IAudioTrack',['../classIAudioTrack.html',1,'']]],
  ['icon_3',['Icon',['../classIcon.html',1,'']]],
  ['iconframe_5fmm7_4',['IconFrame_MM7',['../structIconFrame__MM7.html',1,'']]],
  ['iconframetable_5',['IconFrameTable',['../structIconFrameTable.html',1,'']]],
  ['ikeyboardcontroller_6',['IKeyboardController',['../classIo_1_1IKeyboardController.html',1,'Io']]],
  ['iless_7',['ILess',['../structILess.html',1,'']]],
  ['image_8',['Image',['../classImage.html',1,'']]],
  ['image16bit_5flod_5floader_9',['Image16bit_LOD_Loader',['../classImage16bit__LOD__Loader.html',1,'']]],
  ['image_3c_20color_20_3e_10',['Image&lt; Color &gt;',['../classImage.html',1,'']]],
  ['image_3c_20uint8_5ft_20_3e_11',['Image&lt; uint8_t &gt;',['../classImage.html',1,'']]],
  ['imagebase_12',['ImageBase',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20color_2c_20std_3a_3aunique_5fptr_3c_20color_2c_20freedeleter_20_3e_20_3e_13',['ImageBase&lt; Color, std::unique_ptr&lt; Color, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20const_20t_2c_20detail_3a_3aviewpointer_3c_20const_20t_20_3e_20_3e_14',['ImageBase&lt; const T, detail::ViewPointer&lt; const T &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20t_2c_20std_3a_3aunique_5fptr_3c_20t_2c_20freedeleter_20_3e_20_3e_15',['ImageBase&lt; T, std::unique_ptr&lt; T, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20uint8_5ft_2c_20std_3a_3aunique_5fptr_3c_20uint8_5ft_2c_20freedeleter_20_3e_20_3e_16',['ImageBase&lt; uint8_t, std::unique_ptr&lt; uint8_t, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagehelper_17',['ImageHelper',['../classImageHelper.html',1,'']]],
  ['imageloader_18',['ImageLoader',['../classImageLoader.html',1,'']]],
  ['imageview_19',['ImageView',['../classImageView.html',1,'']]],
  ['img_20',['img',['../structimg.html',1,'']]],
  ['imovie_21',['IMovie',['../classIMovie.html',1,'']]],
  ['indexedarray_22',['IndexedArray',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bonusrange_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_23',['IndexedArray&lt; BonusRange, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20house_5ffirst_5farcomage_5ftavern_2c_20house_5flast_5farcomage_5ftavern_20_3e_24',['IndexedArray&lt; bool, HOUSE_FIRST_ARCOMAGE_TAVERN, HOUSE_LAST_ARCOMAGE_TAVERN &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_25',['IndexedArray&lt; bool, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20item_5ffirst_5fspawnable_5fartifact_2c_20item_5flast_5fspawnable_5fartifact_20_3e_26',['IndexedArray&lt; bool, ITEM_FIRST_SPAWNABLE_ARTIFACT, ITEM_LAST_SPAWNABLE_ARTIFACT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20platformkey_3a_3akey_5ffirst_2c_20platformkey_3a_3akey_5flast_20_3e_27',['IndexedArray&lt; bool, PlatformKey::KEY_FIRST, PlatformKey::KEY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20spell_5ffirst_5fregular_2c_20spell_5flast_5fregular_20_3e_28',['IndexedArray&lt; bool, SPELL_FIRST_REGULAR, SPELL_LAST_REGULAR &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20char_2c_20item_5ftype_5ffirst_5fspecial_5fenchantable_2c_20item_5ftype_5flast_5fspecial_5fenchantable_20_3e_29',['IndexedArray&lt; char, ITEM_TYPE_FIRST_SPECIAL_ENCHANTABLE, ITEM_TYPE_LAST_SPECIAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20combinedskillvalue_2c_20character_5fskill_5ffirst_2c_20character_5fskill_5flast_20_3e_30',['IndexedArray&lt; CombinedSkillValue, CHARACTER_SKILL_FIRST, CHARACTER_SKILL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20character_5fattribute_5ffirst_5fstat_2c_20character_5fattribute_5flast_5fstat_20_3e_31',['IndexedArray&lt; const char *, CHARACTER_ATTRIBUTE_FIRST_STAT, CHARACTER_ATTRIBUTE_LAST_STAT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20character_5fbuff_5ffirst_2c_20character_5fbuff_5flast_20_3e_32',['IndexedArray&lt; const char *, CHARACTER_BUFF_FIRST, CHARACTER_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20character_5fskill_5finvalid_2c_20character_5fskill_5flast_5fvisible_20_3e_33',['IndexedArray&lt; const char *, CHARACTER_SKILL_INVALID, CHARACTER_SKILL_LAST_VISIBLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20class_5ffirst_2c_20class_5flast_20_3e_34',['IndexedArray&lt; const char *, CLASS_FIRST, CLASS_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20condition_5ffirst_2c_20condition_5flast_20_3e_35',['IndexedArray&lt; const char *, CONDITION_FIRST, CONDITION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_36',['IndexedArray&lt; const char *, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20npc_5fprofession_5ffirst_2c_20npc_5fprofession_5flast_20_3e_37',['IndexedArray&lt; const char *, NPC_PROFESSION_FIRST, NPC_PROFESSION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20const_20char_20_2a_2c_20party_5fbuff_5ffirst_2c_20party_5fbuff_5flast_20_3e_38',['IndexedArray&lt; const char *, PARTY_BUFF_FIRST, PARTY_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20duration_2c_20character_5fskill_5fmastery_5ffirst_2c_20character_5fskill_5fmastery_5flast_20_3e_39',['IndexedArray&lt; Duration, CHARACTER_SKILL_MASTERY_FIRST, CHARACTER_SKILL_MASTERY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20graphicsimage_20_2a_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_40',['IndexedArray&lt; GraphicsImage *, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20itemid_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_41',['IndexedArray&lt; IndexedArray&lt; ItemId, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20monsterhostility_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_42',['IndexedArray&lt; IndexedArray&lt; MonsterHostility, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20uint16_5ft_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_43',['IndexedArray&lt; IndexedArray&lt; uint16_t, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_44',['IndexedArray&lt; int, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20sex_5ffirst_2c_20sex_5flast_20_3e_45',['IndexedArray&lt; int, SEX_FIRST, SEX_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemdesc_2c_20item_5ffirst_5fvalid_2c_20item_5flast_5fvalid_20_3e_46',['IndexedArray&lt; ItemDesc, ITEM_FIRST_VALID, ITEM_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemenchantmenttable_2c_20character_5fattribute_5ffirst_5fenchantable_2c_20character_5fattribute_5flast_5fenchantable_20_3e_47',['IndexedArray&lt; ItemEnchantmentTable, CHARACTER_ATTRIBUTE_FIRST_ENCHANTABLE, CHARACTER_ATTRIBUTE_LAST_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemid_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_48',['IndexedArray&lt; ItemId, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemspecialenchantmenttable_2c_20item_5fenchantment_5ffirst_5fvalid_2c_20item_5fenchantment_5flast_5fvalid_20_3e_49',['IndexedArray&lt; ItemSpecialEnchantmentTable, ITEM_ENCHANTMENT_FIRST_VALID, ITEM_ENCHANTMENT_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20mapinfo_2c_20map_5ffirst_2c_20map_5flast_20_3e_50',['IndexedArray&lt; MapInfo, MAP_FIRST, MAP_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterdesc_2c_20monster_5ffirst_2c_20monster_5flast_20_3e_51',['IndexedArray&lt; MonsterDesc, MONSTER_FIRST, MONSTER_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterhostility_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_52',['IndexedArray&lt; MonsterHostility, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterid_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_53',['IndexedArray&lt; MonsterId, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterinfo_2c_20monster_5ffirst_2c_20monster_5flast_20_3e_54',['IndexedArray&lt; MonsterInfo, MONSTER_FIRST, MONSTER_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20npcprofession_2c_20npc_5fprofession_5ffirst_2c_20npc_5fprofession_5flast_20_3e_55',['IndexedArray&lt; NPCProfession, NPC_PROFESSION_FIRST, NPC_PROFESSION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20soundid_2c_20actor_5fsound_5ffirst_2c_20actor_5fsound_5flast_20_3e_56',['IndexedArray&lt; SoundId, ACTOR_SOUND_FIRST, ACTOR_SOUND_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20actor_5fbuff_5ffirst_2c_20actor_5fbuff_5flast_20_3e_57',['IndexedArray&lt; SpellBuff, ACTOR_BUFF_FIRST, ACTOR_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20character_5fbuff_5ffirst_2c_20character_5fbuff_5flast_20_3e_58',['IndexedArray&lt; SpellBuff, CHARACTER_BUFF_FIRST, CHARACTER_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20party_5fbuff_5ffirst_2c_20party_5fbuff_5flast_20_3e_59',['IndexedArray&lt; SpellBuff, PARTY_BUFF_FIRST, PARTY_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellinfo_2c_20spell_5ffirst_5fregular_2c_20spell_5flast_5fregular_20_3e_60',['IndexedArray&lt; SpellInfo, SPELL_FIRST_REGULAR, SPELL_LAST_REGULAR &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20graphicsimage_20_2a_2c_202_20_3e_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_61',['IndexedArray&lt; std::array&lt; GraphicsImage *, 2 &gt;, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20itemgen_2c_2012_20_3e_2c_20house_5ffirst_5fmagic_5fguild_2c_20house_5flast_5fmagic_5fguild_20_3e_62',['IndexedArray&lt; std::array&lt; ItemGen, 12 &gt;, HOUSE_FIRST_MAGIC_GUILD, HOUSE_LAST_MAGIC_GUILD &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20itemgen_2c_2012_20_3e_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_63',['IndexedArray&lt; std::array&lt; ItemGen, 12 &gt;, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3acondition_5fvariable_2c_20side_5fgame_2c_20side_5fcontrol_20_3e_64',['IndexedArray&lt; std::condition_variable, SIDE_GAME, SIDE_CONTROL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20anim_5ffirst_2c_20anim_5flast_20_3e_65',['IndexedArray&lt; std::string, ANIM_First, ANIM_Last &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20sex_5ffirst_2c_20sex_5flast_20_3e_66',['IndexedArray&lt; std::string, SEX_FIRST, SEX_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aunique_5fptr_3c_20randomengine_20_3e_2c_20random_5fengine_5ffirst_2c_20random_5fengine_5flast_20_3e_67',['IndexedArray&lt; std::unique_ptr&lt; RandomEngine &gt;, RANDOM_ENGINE_FIRST, RANDOM_ENGINE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3avector_3c_20platformeventfilter_20_2a_20_3e_2c_20event_5ffirst_2c_20event_5flast_20_3e_68',['IndexedArray&lt; std::vector&lt; PlatformEventFilter * &gt;, EVENT_FIRST, EVENT_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20condition_5ffirst_2c_20condition_5flast_20_3e_69',['IndexedArray&lt; Time, CONDITION_FIRST, CONDITION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5fmagic_5fguild_2c_20house_5flast_5fmagic_5fguild_20_3e_70',['IndexedArray&lt; Time, HOUSE_FIRST_MAGIC_GUILD, HOUSE_LAST_MAGIC_GUILD &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_71',['IndexedArray&lt; Time, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_72',['IndexedArray&lt; Time, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20anim_5ffirst_2c_20anim_5flast_20_3e_73',['IndexedArray&lt; uint16_t, ANIM_First, ANIM_Last &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20character_5fskill_5fmastery_5ffirst_2c_20character_5fskill_5fmastery_5flast_20_3e_74',['IndexedArray&lt; uint16_t, CHARACTER_SKILL_MASTERY_FIRST, CHARACTER_SKILL_MASTERY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_75',['IndexedArray&lt; uint16_t, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint8_5ft_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_76',['IndexedArray&lt; uint8_t, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20char_2c_20item_5ftype_5ffirst_5fnormal_5fenchantable_2c_20item_5ftype_5flast_5fnormal_5fenchantable_20_3e_77',['IndexedArray&lt; unsigned char, ITEM_TYPE_FIRST_NORMAL_ENCHANTABLE, ITEM_TYPE_LAST_NORMAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20int_2c_20item_5fslot_5ffirst_5fvalid_2c_20item_5fslot_5flast_5fvalid_20_3e_78',['IndexedArray&lt; unsigned int, ITEM_SLOT_FIRST_VALID, ITEM_SLOT_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20int_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_79',['IndexedArray&lt; unsigned int, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20int_2c_20item_5ftype_5ffirst_5fnormal_5fenchantable_2c_20item_5ftype_5flast_5fnormal_5fenchantable_20_3e_80',['IndexedArray&lt; unsigned int, ITEM_TYPE_FIRST_NORMAL_ENCHANTABLE, ITEM_TYPE_LAST_NORMAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedbitset_81',['IndexedBitset',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_201_2c_20208_20_3e_82',['IndexedBitset&lt; 1, 208 &gt;',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_201_2c_20512_20_3e_83',['IndexedBitset&lt; 1, 512 &gt;',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_20qbit_5ffirst_2c_20qbit_5flast_20_3e_84',['IndexedBitset&lt; QBIT_FIRST, QBIT_LAST &gt;',['../classIndexedBitset.html',1,'']]],
  ['indoordelta_5fmm7_85',['IndoorDelta_MM7',['../structIndoorDelta__MM7.html',1,'']]],
  ['indoorlocation_86',['IndoorLocation',['../structIndoorLocation.html',1,'']]],
  ['indoorlocation_5fmm7_87',['IndoorLocation_MM7',['../structIndoorLocation__MM7.html',1,'']]],
  ['inputstream_88',['InputStream',['../classInputStream.html',1,'']]],
  ['int_5fmm_89',['Int_MM',['../structInt__MM.html',1,'']]],
  ['is_5fmemcopy_5fserializable_90',['is_memcopy_serializable',['../structis__memcopy__serializable.html',1,'']]],
  ['is_5fproxy_5fbinarizable_91',['is_proxy_binarizable',['../structis__proxy__binarizable.html',1,'']]],
  ['is_5fproxy_5fbinarizable_3c_20container_20_3e_92',['is_proxy_binarizable&lt; Container &gt;',['../structis__proxy__binarizable_3_01Container_01_4.html',1,'']]],
  ['is_5fproxy_5fbinarizable_3c_20std_3a_3aarray_3c_20t_2c_20n_20_3e_20_3e_93',['is_proxy_binarizable&lt; std::array&lt; T, N &gt; &gt;',['../structis__proxy__binarizable_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsink_94',['is_proxy_binary_sink',['../structis__proxy__binary__sink.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsink_3c_20blob_20_3e_95',['is_proxy_binary_sink&lt; Blob &gt;',['../structis__proxy__binary__sink_3_01Blob_01_4.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsource_96',['is_proxy_binary_source',['../structis__proxy__binary__source.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsource_3c_20blob_20_3e_97',['is_proxy_binary_source&lt; Blob &gt;',['../structis__proxy__binary__source_3_01Blob_01_4.html',1,'']]],
  ['is_5fspan_98',['is_span',['../structdetail_1_1is__span.html',1,'detail']]],
  ['is_5fspan_3c_20std_3a_3aspan_3c_20t_2c_20n_20_3e_20_3e_99',['is_span&lt; std::span&lt; T, N &gt; &gt;',['../structdetail_1_1is__span_3_01std_1_1span_3_01T_00_01N_01_4_01_4.html',1,'detail']]],
  ['item_5fvariation_100',['ITEM_VARIATION',['../structITEM__VARIATION.html',1,'']]],
  ['itemdesc_101',['ItemDesc',['../structItemDesc.html',1,'']]],
  ['itemenchantmenttable_102',['ItemEnchantmentTable',['../structItemEnchantmentTable.html',1,'']]],
  ['itemgen_103',['ItemGen',['../structItemGen.html',1,'']]],
  ['itemgen_5fmm7_104',['ItemGen_MM7',['../structItemGen__MM7.html',1,'']]],
  ['itemspecialenchantmenttable_105',['ItemSpecialEnchantmentTable',['../structItemSpecialEnchantmentTable.html',1,'']]],
  ['itemtable_106',['ItemTable',['../structItemTable.html',1,'']]],
  ['ivideodatasource_107',['IVideoDataSource',['../classIVideoDataSource.html',1,'']]]
];
