var searchData=
[
  ['iaudiodatasource_0',['IAudioDataSource',['../classIAudioDataSource.html',1,'']]],
  ['iaudiosample_1',['IAudioSample',['../classIAudioSample.html',1,'']]],
  ['iaudiotrack_2',['IAudioTrack',['../classIAudioTrack.html',1,'']]],
  ['ibindings_3',['IBindings',['../classIBindings.html',1,'']]],
  ['iconframedata_4',['IconFrameData',['../structIconFrameData.html',1,'']]],
  ['iconframedata_5fmm7_5',['IconFrameData_MM7',['../structIconFrameData__MM7.html',1,'']]],
  ['iconframetable_6',['IconFrameTable',['../classIconFrameTable.html',1,'']]],
  ['image_7',['Image',['../classImage.html',1,'']]],
  ['image16bit_5flod_5floader_8',['Image16bit_LOD_Loader',['../classImage16bit__LOD__Loader.html',1,'']]],
  ['image_3c_20color_20_3e_9',['Image&lt; Color &gt;',['../classImage.html',1,'']]],
  ['image_3c_20int16_5ft_20_3e_10',['Image&lt; int16_t &gt;',['../classImage.html',1,'']]],
  ['image_3c_20std_3a_3aarray_3c_20vec3_2c_202_20_3e_20_3e_11',['Image&lt; std::array&lt; Vec3, 2 &gt; &gt;',['../classImage.html',1,'']]],
  ['image_3c_20uint8_5ft_20_3e_12',['Image&lt; uint8_t &gt;',['../classImage.html',1,'']]],
  ['imagebase_13',['ImageBase',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20color_2c_20std_3a_3aunique_5fptr_3c_20color_2c_20freedeleter_20_3e_20_3e_14',['ImageBase&lt; Color, std::unique_ptr&lt; Color, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20const_20t_2c_20detail_3a_3aviewpointer_3c_20const_20t_20_3e_20_3e_15',['ImageBase&lt; const T, detail::ViewPointer&lt; const T &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20int16_5ft_2c_20std_3a_3aunique_5fptr_3c_20int16_5ft_2c_20freedeleter_20_3e_20_3e_16',['ImageBase&lt; int16_t, std::unique_ptr&lt; int16_t, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20std_3a_3aarray_3c_20vec3_2c_202_20_3e_2c_20std_3a_3aunique_5fptr_3c_20std_3a_3aarray_3c_20vec3_2c_202_20_3e_2c_20freedeleter_20_3e_20_3e_17',['ImageBase&lt; std::array&lt; Vec3, 2 &gt;, std::unique_ptr&lt; std::array&lt; Vec3, 2 &gt;, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20t_2c_20std_3a_3aunique_5fptr_3c_20t_2c_20freedeleter_20_3e_20_3e_18',['ImageBase&lt; T, std::unique_ptr&lt; T, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagebase_3c_20uint8_5ft_2c_20std_3a_3aunique_5fptr_3c_20uint8_5ft_2c_20freedeleter_20_3e_20_3e_19',['ImageBase&lt; uint8_t, std::unique_ptr&lt; uint8_t, FreeDeleter &gt; &gt;',['../classdetail_1_1ImageBase.html',1,'detail']]],
  ['imagehelper_20',['ImageHelper',['../classImageHelper.html',1,'']]],
  ['imageloader_21',['ImageLoader',['../classImageLoader.html',1,'']]],
  ['imageview_22',['ImageView',['../classImageView.html',1,'']]],
  ['imguibindings_23',['ImGuiBindings',['../classImGuiBindings.html',1,'']]],
  ['imguiinputtextuserdata_24',['ImGuiInputTextUserData',['../structImGuiInputTextUserData.html',1,'']]],
  ['imovie_25',['IMovie',['../classIMovie.html',1,'']]],
  ['indexedarray_26',['IndexedArray',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20attribute_5ffirst_5fstat_2c_20attribute_5flast_5fstat_20_3e_27',['IndexedArray&lt; bool, ATTRIBUTE_FIRST_STAT, ATTRIBUTE_LAST_STAT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20house_5ffirst_5farcomage_5ftavern_2c_20house_5flast_5farcomage_5ftavern_20_3e_28',['IndexedArray&lt; bool, HOUSE_FIRST_ARCOMAGE_TAVERN, HOUSE_LAST_ARCOMAGE_TAVERN &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_29',['IndexedArray&lt; bool, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20item_5ffirst_5fspawnable_5fartifact_2c_20item_5flast_5fspawnable_5fartifact_20_3e_30',['IndexedArray&lt; bool, ITEM_FIRST_SPAWNABLE_ARTIFACT, ITEM_LAST_SPAWNABLE_ARTIFACT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20platformkey_3a_3akey_5ffirst_2c_20platformkey_3a_3akey_5flast_20_3e_31',['IndexedArray&lt; bool, PlatformKey::KEY_FIRST, PlatformKey::KEY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20bool_2c_20spell_5ffirst_5fregular_2c_20spell_5flast_5fregular_20_3e_32',['IndexedArray&lt; bool, SPELL_FIRST_REGULAR, SPELL_LAST_REGULAR &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20char_2c_20item_5ftype_5ffirst_5fspecial_5fenchantable_2c_20item_5ftype_5flast_5fspecial_5fenchantable_20_3e_33',['IndexedArray&lt; char, ITEM_TYPE_FIRST_SPECIAL_ENCHANTABLE, ITEM_TYPE_LAST_SPECIAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20combinedskillvalue_2c_20skill_5ffirst_2c_20skill_5flast_20_3e_34',['IndexedArray&lt; CombinedSkillValue, SKILL_FIRST, SKILL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20duration_2c_20mastery_5ffirst_2c_20mastery_5flast_20_3e_35',['IndexedArray&lt; Duration, MASTERY_FIRST, MASTERY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20graphicsimage_20_2a_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_36',['IndexedArray&lt; GraphicsImage *, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20itemid_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_37',['IndexedArray&lt; IndexedArray&lt; ItemId, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20monsterhostility_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_38',['IndexedArray&lt; IndexedArray&lt; MonsterHostility, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20indexedarray_3c_20uint16_5ft_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_39',['IndexedArray&lt; IndexedArray&lt; uint16_t, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20attribute_5ffirst_5fstat_2c_20attribute_5flast_5fstat_20_3e_40',['IndexedArray&lt; int, ATTRIBUTE_FIRST_STAT, ATTRIBUTE_LAST_STAT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_41',['IndexedArray&lt; int, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20item_5fslot_5ffirst_5fvalid_2c_20item_5fslot_5flast_5fvalid_20_3e_42',['IndexedArray&lt; int, ITEM_SLOT_FIRST_VALID, ITEM_SLOT_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_43',['IndexedArray&lt; int, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20int_2c_20sex_5ffirst_2c_20sex_5flast_20_3e_44',['IndexedArray&lt; int, SEX_FIRST, SEX_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemdata_2c_20item_5ffirst_5fvalid_2c_20item_5flast_5fvalid_20_3e_45',['IndexedArray&lt; ItemData, ITEM_FIRST_VALID, ITEM_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20itemid_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_46',['IndexedArray&lt; ItemId, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20mapinfo_2c_20map_5ffirst_2c_20map_5flast_20_3e_47',['IndexedArray&lt; MapInfo, MAP_FIRST, MAP_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterdesc_2c_20monster_5ffirst_2c_20monster_5flast_20_3e_48',['IndexedArray&lt; MonsterDesc, MONSTER_FIRST, MONSTER_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterhostility_2c_20monster_5ftype_5finvalid_2c_20monster_5ftype_5flast_20_3e_49',['IndexedArray&lt; MonsterHostility, MONSTER_TYPE_INVALID, MONSTER_TYPE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterid_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_50',['IndexedArray&lt; MonsterId, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20monsterinfo_2c_20monster_5ffirst_2c_20monster_5flast_20_3e_51',['IndexedArray&lt; MonsterInfo, MONSTER_FIRST, MONSTER_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20npcprofession_2c_20npc_5fprofession_5ffirst_2c_20npc_5fprofession_5flast_20_3e_52',['IndexedArray&lt; NPCProfession, NPC_PROFESSION_FIRST, NPC_PROFESSION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20segment_3c_20int_20_3e_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_53',['IndexedArray&lt; Segment&lt; int &gt;, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20size_2c_20item_5ffirst_5fvalid_2c_20item_5flast_5fvalid_20_3e_54',['IndexedArray&lt; Size, ITEM_FIRST_VALID, ITEM_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20soundid_2c_20actor_5fsound_5ffirst_2c_20actor_5fsound_5flast_20_3e_55',['IndexedArray&lt; SoundId, ACTOR_SOUND_FIRST, ACTOR_SOUND_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20specialenchantmentdata_2c_20item_5fenchantment_5ffirst_5fvalid_2c_20item_5fenchantment_5flast_5fvalid_20_3e_56',['IndexedArray&lt; SpecialEnchantmentData, ITEM_ENCHANTMENT_FIRST_VALID, ITEM_ENCHANTMENT_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20actor_5fbuff_5ffirst_2c_20actor_5fbuff_5flast_20_3e_57',['IndexedArray&lt; SpellBuff, ACTOR_BUFF_FIRST, ACTOR_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20character_5fbuff_5ffirst_2c_20character_5fbuff_5flast_20_3e_58',['IndexedArray&lt; SpellBuff, CHARACTER_BUFF_FIRST, CHARACTER_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellbuff_2c_20party_5fbuff_5ffirst_2c_20party_5fbuff_5flast_20_3e_59',['IndexedArray&lt; SpellBuff, PARTY_BUFF_FIRST, PARTY_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20spellinfo_2c_20spell_5ffirst_5fregular_2c_20spell_5flast_5fregular_20_3e_60',['IndexedArray&lt; SpellInfo, SPELL_FIRST_REGULAR, SPELL_LAST_REGULAR &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20standardenchantmentdata_2c_20attribute_5ffirst_5fenchantable_2c_20attribute_5flast_5fenchantable_20_3e_61',['IndexedArray&lt; StandardEnchantmentData, ATTRIBUTE_FIRST_ENCHANTABLE, ATTRIBUTE_LAST_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20graphicsimage_20_2a_2c_202_20_3e_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_62',['IndexedArray&lt; std::array&lt; GraphicsImage *, 2 &gt;, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20item_2c_2012_20_3e_2c_20house_5ffirst_5fmagic_5fguild_2c_20house_5flast_5fmagic_5fguild_20_3e_63',['IndexedArray&lt; std::array&lt; Item, 12 &gt;, HOUSE_FIRST_MAGIC_GUILD, HOUSE_LAST_MAGIC_GUILD &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aarray_3c_20item_2c_2012_20_3e_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_64',['IndexedArray&lt; std::array&lt; Item, 12 &gt;, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3acondition_5fvariable_2c_20side_5fgame_2c_20side_5fcontrol_20_3e_65',['IndexedArray&lt; std::condition_variable, SIDE_GAME, SIDE_CONTROL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3afunction_3c_20void_28const_20std_3a_3atype_5finfo_20_26_2c_20const_20void_20_2a_29_3e_2c_20call_5ffirst_2c_20call_5flast_20_3e_66',['IndexedArray&lt; std::function&lt; void(const std::type_info &amp;, const void *)&gt;, CALL_FIRST, CALL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20actor_5fbuff_5ffirst_2c_20actor_5fbuff_5flast_20_3e_67',['IndexedArray&lt; std::string, ACTOR_BUFF_FIRST, ACTOR_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20anim_5ffirst_2c_20anim_5flast_20_3e_68',['IndexedArray&lt; std::string, ANIM_First, ANIM_Last &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20attribute_5ffirst_5fstat_2c_20attribute_5flast_5fstat_20_3e_69',['IndexedArray&lt; std::string, ATTRIBUTE_FIRST_STAT, ATTRIBUTE_LAST_STAT &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20character_5fbuff_5ffirst_2c_20character_5fbuff_5flast_20_3e_70',['IndexedArray&lt; std::string, CHARACTER_BUFF_FIRST, CHARACTER_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20class_5ffirst_2c_20class_5flast_20_3e_71',['IndexedArray&lt; std::string, CLASS_FIRST, CLASS_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20condition_5ffirst_2c_20condition_5flast_20_3e_72',['IndexedArray&lt; std::string, CONDITION_FIRST, CONDITION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20lstr_5ffirst_2c_20lstr_5flast_20_3e_73',['IndexedArray&lt; std::string, LSTR_FIRST, LSTR_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20magic_5fschool_5ffirst_2c_20magic_5fschool_5flast_20_3e_74',['IndexedArray&lt; std::string, MAGIC_SCHOOL_FIRST, MAGIC_SCHOOL_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20mastery_5ffirst_2c_20mastery_5flast_20_3e_75',['IndexedArray&lt; std::string, MASTERY_FIRST, MASTERY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20monster_5fspecial_5fability_5ffirst_2c_20monster_5fspecial_5fability_5flast_20_3e_76',['IndexedArray&lt; std::string, MONSTER_SPECIAL_ABILITY_FIRST, MONSTER_SPECIAL_ABILITY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20npc_5fprofession_5ffirst_2c_20npc_5fprofession_5flast_20_3e_77',['IndexedArray&lt; std::string, NPC_PROFESSION_FIRST, NPC_PROFESSION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20party_5fbuff_5ffirst_2c_20party_5fbuff_5flast_20_3e_78',['IndexedArray&lt; std::string, PARTY_BUFF_FIRST, PARTY_BUFF_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20sex_5ffirst_2c_20sex_5flast_20_3e_79',['IndexedArray&lt; std::string, SEX_FIRST, SEX_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20skill_5finvalid_2c_20skill_5flast_5fvisible_20_3e_80',['IndexedArray&lt; std::string, SKILL_INVALID, SKILL_LAST_VISIBLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3astring_2c_20special_5fattack_5ffirst_2c_20special_5fattack_5flast_20_3e_81',['IndexedArray&lt; std::string, SPECIAL_ATTACK_FIRST, SPECIAL_ATTACK_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3aunique_5fptr_3c_20randomengine_20_3e_2c_20random_5fengine_5ffirst_2c_20random_5fengine_5flast_20_3e_82',['IndexedArray&lt; std::unique_ptr&lt; RandomEngine &gt;, RANDOM_ENGINE_FIRST, RANDOM_ENGINE_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20std_3a_3avector_3c_20platformeventfilter_20_2a_20_3e_2c_20event_5ffirst_2c_20event_5flast_20_3e_83',['IndexedArray&lt; std::vector&lt; PlatformEventFilter * &gt;, EVENT_FIRST, EVENT_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20condition_5ffirst_2c_20condition_5flast_20_3e_84',['IndexedArray&lt; Time, CONDITION_FIRST, CONDITION_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5fmagic_5fguild_2c_20house_5flast_5fmagic_5fguild_20_3e_85',['IndexedArray&lt; Time, HOUSE_FIRST_MAGIC_GUILD, HOUSE_LAST_MAGIC_GUILD &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5fshop_2c_20house_5flast_5fshop_20_3e_86',['IndexedArray&lt; Time, HOUSE_FIRST_SHOP, HOUSE_LAST_SHOP &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20time_2c_20house_5ffirst_5ftown_5fhall_2c_20house_5flast_5ftown_5fhall_20_3e_87',['IndexedArray&lt; Time, HOUSE_FIRST_TOWN_HALL, HOUSE_LAST_TOWN_HALL &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20anim_5ffirst_2c_20anim_5flast_20_3e_88',['IndexedArray&lt; uint16_t, ANIM_First, ANIM_Last &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20item_5ffirst_5freal_5fpotion_2c_20item_5flast_5freal_5fpotion_20_3e_89',['IndexedArray&lt; uint16_t, ITEM_FIRST_REAL_POTION, ITEM_LAST_REAL_POTION &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint16_5ft_2c_20mastery_5ffirst_2c_20mastery_5flast_20_3e_90',['IndexedArray&lt; uint16_t, MASTERY_FIRST, MASTERY_LAST &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20uint8_5ft_2c_20arena_5flevel_5ffirst_5fvalid_2c_20arena_5flevel_5flast_5fvalid_20_3e_91',['IndexedArray&lt; uint8_t, ARENA_LEVEL_FIRST_VALID, ARENA_LEVEL_LAST_VALID &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20char_2c_20item_5ftype_5ffirst_5fnormal_5fenchantable_2c_20item_5ftype_5flast_5fnormal_5fenchantable_20_3e_92',['IndexedArray&lt; unsigned char, ITEM_TYPE_FIRST_NORMAL_ENCHANTABLE, ITEM_TYPE_LAST_NORMAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20int_2c_20item_5ftreasure_5flevel_5ffirst_5frandom_2c_20item_5ftreasure_5flevel_5flast_5frandom_20_3e_93',['IndexedArray&lt; unsigned int, ITEM_TREASURE_LEVEL_FIRST_RANDOM, ITEM_TREASURE_LEVEL_LAST_RANDOM &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedarray_3c_20unsigned_20int_2c_20item_5ftype_5ffirst_5fnormal_5fenchantable_2c_20item_5ftype_5flast_5fnormal_5fenchantable_20_3e_94',['IndexedArray&lt; unsigned int, ITEM_TYPE_FIRST_NORMAL_ENCHANTABLE, ITEM_TYPE_LAST_NORMAL_ENCHANTABLE &gt;',['../classIndexedArray.html',1,'']]],
  ['indexedbitset_95',['IndexedBitset',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_201_2c_20208_20_3e_96',['IndexedBitset&lt; 1, 208 &gt;',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_201_2c_20512_20_3e_97',['IndexedBitset&lt; 1, 512 &gt;',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_20award_5ffirst_2c_20award_5flast_20_3e_98',['IndexedBitset&lt; AWARD_FIRST, AWARD_LAST &gt;',['../classIndexedBitset.html',1,'']]],
  ['indexedbitset_3c_20qbit_5ffirst_2c_20qbit_5flast_20_3e_99',['IndexedBitset&lt; QBIT_FIRST, QBIT_LAST &gt;',['../classIndexedBitset.html',1,'']]],
  ['indoordelta_5fmm7_100',['IndoorDelta_MM7',['../structIndoorDelta__MM7.html',1,'']]],
  ['indoorlocation_101',['IndoorLocation',['../structIndoorLocation.html',1,'']]],
  ['indoorlocation_5fmm7_102',['IndoorLocation_MM7',['../structIndoorLocation__MM7.html',1,'']]],
  ['inputbindings_103',['InputBindings',['../classInputBindings.html',1,'']]],
  ['inputscripteventhandler_104',['InputScriptEventHandler',['../classInputScriptEventHandler.html',1,'']]],
  ['inputstream_105',['InputStream',['../classInputStream.html',1,'']]],
  ['int_5fmm_106',['Int_MM',['../structInt__MM.html',1,'']]],
  ['inventory_107',['Inventory',['../classInventory.html',1,'']]],
  ['inventoryconstentry_108',['InventoryConstEntry',['../classInventoryConstEntry.html',1,'']]],
  ['inventoryentry_109',['InventoryEntry',['../classInventoryEntry.html',1,'']]],
  ['inventoryrecord_110',['InventoryRecord',['../structInventory_1_1InventoryRecord.html',1,'Inventory']]],
  ['is_5fmemcopy_5fserializable_111',['is_memcopy_serializable',['../structis__memcopy__serializable.html',1,'']]],
  ['is_5fproxy_5fbinarizable_112',['is_proxy_binarizable',['../structis__proxy__binarizable.html',1,'']]],
  ['is_5fproxy_5fbinarizable_3c_20container_20_3e_113',['is_proxy_binarizable&lt; Container &gt;',['../structis__proxy__binarizable_3_01Container_01_4.html',1,'']]],
  ['is_5fproxy_5fbinarizable_3c_20std_3a_3aarray_3c_20t_2c_20n_20_3e_20_3e_114',['is_proxy_binarizable&lt; std::array&lt; T, N &gt; &gt;',['../structis__proxy__binarizable_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsink_115',['is_proxy_binary_sink',['../structis__proxy__binary__sink.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsink_3c_20blob_20_3e_116',['is_proxy_binary_sink&lt; Blob &gt;',['../structis__proxy__binary__sink_3_01Blob_01_4.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsource_117',['is_proxy_binary_source',['../structis__proxy__binary__source.html',1,'']]],
  ['is_5fproxy_5fbinary_5fsource_3c_20blob_20_3e_118',['is_proxy_binary_source&lt; Blob &gt;',['../structis__proxy__binary__source_3_01Blob_01_4.html',1,'']]],
  ['is_5fspan_119',['is_span',['../structdetail_1_1is__span.html',1,'detail']]],
  ['is_5fspan_3c_20std_3a_3aspan_3c_20t_2c_20n_20_3e_20_3e_120',['is_span&lt; std::span&lt; T, N &gt; &gt;',['../structdetail_1_1is__span_3_01std_1_1span_3_01T_00_01N_01_4_01_4.html',1,'detail']]],
  ['item_121',['Item',['../structItem.html',1,'']]],
  ['item_5fmm7_122',['Item_MM7',['../structItem__MM7.html',1,'']]],
  ['item_5fvariation_123',['ITEM_VARIATION',['../structITEM__VARIATION.html',1,'']]],
  ['itemdata_124',['ItemData',['../structItemData.html',1,'']]],
  ['itemtable_125',['ItemTable',['../structItemTable.html',1,'']]],
  ['ivideodatasource_126',['IVideoDataSource',['../classIVideoDataSource.html',1,'']]]
];
