
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/local/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:6 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/ubuntu/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/local/share/npm-global/bin/"
    searched_directories:
      - "/home/ubuntu/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/ubuntu/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/local/share/npm-global/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.12.76-linuxkit - aarch64
  -
    kind: "find-v1"
    backtrace:
      - "/usr/local/share/cmake-4.3/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:6 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/home/ubuntu/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/local/share/npm-global/bin/"
    searched_directories:
      - "/home/ubuntu/.local/bin/gmake"
      - "/usr/local/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/usr/sbin/gmake"
      - "/usr/bin/gmake"
      - "/sbin/gmake"
      - "/bin/gmake"
      - "/usr/local/share/npm-global/bin/gmake"
      - "/home/ubuntu/.local/bin/make"
      - "/usr/local/sbin/make"
      - "/usr/local/bin/make"
      - "/usr/sbin/make"
      - "/usr/bin/make"
      - "/sbin/make"
      - "/bin/make"
      - "/usr/local/share/npm-global/bin/make"
      - "/home/ubuntu/.local/bin/smake"
      - "/usr/local/sbin/smake"
      - "/usr/local/bin/smake"
      - "/usr/sbin/smake"
      - "/usr/bin/smake"
      - "/sbin/smake"
      - "/bin/smake"
      - "/usr/local/share/npm-global/bin/smake"
    found: false
    search_context:
      ENV{PATH}:
        - "/home/ubuntu/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/local/share/npm-global/bin"
...
