#include "EntitySnapshots.h"

#include <algorithm>
#include <type_traits>
#include <string>
#include <unordered_map>

#include "Engine/Engine.h"
#include "Engine/Graphics/Indoor.h"
#include "Engine/Graphics/Level/Decoration.h"
#include "Engine/Graphics/DecorationList.h"
#include "Engine/Graphics/Outdoor.h"
#include "Engine/Graphics/Overlays.h"
#include "Engine/Graphics/Sprites.h"
#include "Engine/Graphics/TextureFrameTable.h"
#include "Engine/Graphics/Image.h"
#include "Engine/Objects/Actor.h"
#include "Engine/Objects/NPC.h"
#include "Engine/Objects/ObjectList.h"
#include "Engine/Objects/SpriteObject.h"
#include "Engine/Objects/Chest.h"
#include "Engine/Party.h"
#include "Engine/SaveLoad.h"
#include "Engine/Tables/IconFrameTable.h"
#include "Engine/Tables/CharacterFrameTable.h"
#include "Engine/Tables/TileTable.h"
#include "Engine/Time.h"

#include "Media/Audio/SoundInfo.h"

#include "GUI/GUIFont.h"

#include "Library/Color/ColorTable.h"
#include "Library/Snapshots/CommonSnapshots.h"

#include "Utility/Memory/MemSet.h"
#include "Utility/String.h"
#include "Utility/MapAccess.h"

/**
 * Mapping used for beacon map id serialization.
 *
 * DON'T EDIT, THIS IS AUTOGENERATED CODE.
 *
 * @see runBeaconsCodeGen
 */
static const std::unordered_map<MapId, uint16_t> gamesLodIndexByMapId = {
    {MAP_ERATHIAN_SEWERS, 0},
    {MAP_MAZE, 1},
    {MAP_CASTLE_GLOAMING, 2},
    {MAP_TEMPLE_OF_BAA, 3},
    {MAP_ARENA, 4},
    {MAP_TEMPLE_OF_THE_MOON, 5},
    {MAP_THUNDERFIST_MOUNTAIN, 6},
    {MAP_TULAREAN_CAVES, 7},
    {MAP_TITANS_STRONGHOLD, 8},
    {MAP_BREEDING_ZONE, 9},
    {MAP_WALLS_OF_MIST, 10},
    {MAP_CLANKERS_LABORATORY, 11},
    {MAP_ZOKARRS_TOMB, 12},
    {MAP_SCHOOL_OF_SORCERY, 13},
    {MAP_WATCHTOWER_6, 14},
    {MAP_WINE_CELLAR, 15},
    {MAP_TIDEWATER_CAVERNS, 16},
    {MAP_LORD_MARKHAMS_MANOR, 17},
    {MAP_GRAND_TEMPLE_OF_THE_MOON, 18},
    {MAP_MERCENARY_GUILD, 19},
    {MAP_WHITE_CLIFF_CAVE, 20},
    {MAP_HALL_UNDER_THE_HILL, 21},
    {MAP_LINCOLN, 22},
    {MAP_STONE_CITY, 23},
    {MAP_CELESTE, 24},
    {MAP_PIT, 25},
    {MAP_COLONY_ZOD, 26},
    {MAP_DRAGONS_LAIR, 27},
    {MAP_CASTLE_HARMONDALE, 28},
    {MAP_CASTLE_LAMBENT, 29},
    {MAP_FORT_RIVERSTRIDE, 30},
    {MAP_CASTLE_NAVAN, 31},
    {MAP_CASTLE_GRYPHONHEART, 32},
    {MAP_RED_DWARF_MINES, 33},
    {MAP_NIGHON_TUNNELS, 34},
    {MAP_TUNNELS_TO_EEOFOL, 35},
    {MAP_HAUNTED_MANSION, 36},
    {MAP_BARROW_VII, 37},
    {MAP_BARROW_IV, 38},
    {MAP_BARROW_II, 39},
    {MAP_BARROW_XIV, 40},
    {MAP_BARROW_III, 41},
    {MAP_BARROW_X, 42},
    {MAP_BARROW_XII, 43},
    {MAP_BARROW_V, 44},
    {MAP_BARROW_XI, 45},
    {MAP_BARROW_XV, 46},
    {MAP_BARROW_IX, 47},
    {MAP_BARROW_VI, 48},
    {MAP_BARROW_I, 49},
    {MAP_BARROW_VIII, 50},
    {MAP_BARROW_XIII, 51},
    {MAP_WROMTHRAXS_CAVE, 52},
    {MAP_WILLIAM_SETAGS_TOWER, 53},
    {MAP_HIDDEN_TOMB, 54},
    {MAP_DRAGON_CAVES, 55},
    {MAP_BANDIT_CAVES, 56},
    {MAP_SMALL_HOUSE, 57},
    {MAP_STRANGE_TEMPLE, 58},
    {MAP_EMERALD_ISLAND, 59},
    {MAP_HARMONDALE, 60},
    {MAP_ERATHIA, 61},
    {MAP_TULAREAN_FOREST, 62},
    {MAP_DEYJA, 63},
    {MAP_BRACADA_DESERT, 64},
    {MAP_EVENMORN_ISLAND, 65},
    {MAP_MOUNT_NIGHON, 66},
    {MAP_BARROW_DOWNS, 67},
    {MAP_LAND_OF_THE_GIANTS, 68},
    {MAP_TATALIA, 69},
    {MAP_AVLEE, 70},
    {MAP_SHOALS, 71},
    {MAP_TEMPLE_OF_THE_LIGHT, 72},
    {MAP_TEMPLE_OF_THE_DARK, 73},
    {MAP_GRAND_TEMPLE_OF_THE_SUN, 74},
    {MAP_HALL_OF_THE_PIT, 75},
};
static const std::unordered_map<uint16_t, MapId> mapIdByGamesLodIndex = inverted(gamesLodIndexByMapId);

static void snapshot(const GameTime &src, int64_t *dst) {
    *dst = src.value;
}

static void reconstruct(int64_t src, GameTime *dst) {
    dst->value = src;
}

static void snapshot(const CombinedSkillValue &src, uint16_t *dst) {
    *dst = src.joined();
}

static void reconstruct(const uint16_t &src, CombinedSkillValue *dst) {
    *dst = CombinedSkillValue::fromJoined(src);
}

static void snapshot(const MonsterId &src, int16_t *dst) {
    *dst = std::to_underlying(src);
}

static void reconstruct(int16_t src, MonsterId *dst) {
    *dst = static_cast<MonsterId>(src);
}

static void snapshot(const BBoxi &src, BBoxs *dst) {
    // TODO(captainurist): do we need to check for overflows here?
    dst->x1 = src.x1;
    dst->x2 = src.x2;
    dst->y1 = src.y1;
    dst->y2 = src.y2;
    dst->z1 = src.z1;
    dst->z2 = src.z2;
}

static void reconstruct(const BBoxs &src, BBoxi *dst) {
    dst->x1 = src.x1;
    dst->x2 = src.x2;
    dst->y1 = src.y1;
    dst->y2 = src.y2;
    dst->z1 = src.z1;
    dst->z2 = src.z2;
}

void snapshot(const Pid &src, uint16_t *dst) {
    *dst = src.packed();
}

void reconstruct(uint16_t src, Pid *dst) {
    *dst = Pid::fromPacked(src);
}

void snapshot(const Vec3i &src, Vec3s *dst) {
    // TODO(captainurist): do we need to check for overflows here?
    dst->x = src.x;
    dst->y = src.y;
    dst->z = src.z;
}

void reconstruct(const Vec3s &src, Vec3i *dst) {
    dst->x = src.x;
    dst->y = src.y;
    dst->z = src.z;
}

void reconstruct(const Planei_MM7 &src, Planef *dst) {
    dst->normal.x = src.normal.x / 65536.0f;
    dst->normal.y = src.normal.y / 65536.0f;
    dst->normal.z = src.normal.z / 65536.0f;
    dst->dist = src.dist / 65536.0f;
}

void reconstruct(const SpriteFrame_MM7 &src, SpriteFrame *dst) {
    reconstruct(src.iconName, &dst->icon_name);
    dst->icon_name = toLower(dst->icon_name);

    reconstruct(src.textureName, &dst->texture_name);
    dst->texture_name = toLower(dst->texture_name);

    for (unsigned int i = 0; i < 8; ++i)
        dst->hw_sprites[i] = nullptr;

    dst->scale = src.scale / 65536.0f;
    dst->uFlags = src.flags;

    dst->uGlowRadius = src.glowRadius;
    dst->uPaletteID = src.paletteId;
    dst->ResetPaletteIndex(src.paletteIndex);
    dst->uAnimTime = src.animTime;
    dst->uAnimLength = src.animLength;
}

void reconstruct(const BLVFace_MM7 &src, BLVFace *dst) {
    dst->facePlane = src.facePlane;
    dst->zCalc.init(dst->facePlane);
    dst->uAttributes = static_cast<FaceAttributes>(src.attributes);
    dst->pVertexIDs = nullptr;
    dst->pVertexUIDs = nullptr;
    dst->pVertexVIDs = nullptr;
    dst->uFaceExtraID = src.faceExtraId;
    dst->resource = nullptr;
    dst->uSectorID = src.sectorId;
    dst->uBackSectorID = src.backSectorId;
    reconstruct(src.bounding, &dst->pBounding);
    dst->uPolygonType = static_cast<PolygonType>(src.polygonType);
    dst->uNumVertices = src.numVertices;
}

void reconstruct(const TileDesc_MM7 &src, TileDesc *dst) {
    reconstruct(src.tileName, &dst->name);
    dst->name = toLower(dst->name);

    if (istarts_with(dst->name, "wtrdr"))
        dst->name.insert(0, "h");  // mm7 uses hd water tiles with legacy names

    dst->uTileID = src.tileId;
    dst->tileset = static_cast<Tileset>(src.tileSet);
    dst->uSection = static_cast<TILE_SECT>(src.section);
    dst->uAttributes = static_cast<TILE_DESC_FLAGS>(src.attributes);
}

void reconstruct(const TextureFrame_MM7 &src, TextureFrame *dst) {
    reconstruct(src.textureName, &dst->name);
    dst->name = toLower(dst->name);

    dst->animLength = src.animLength;
    dst->animTime = src.animTime;
    dst->flags = static_cast<TextureFrameFlags>(src.flags);
}

void snapshot(const Timer &src, Timer_MM7 *dst) {
    memzero(dst);

    dst->ready = src.bReady;
    dst->paused = src.bPaused;
    dst->tackGameTime = src.bTackGameTime;
    dst->startTime = src.uStartTime;
    dst->stopTime = src.uStopTime;
    dst->gameTimeStart = src.uGameTimeStart;
    dst->timeElapsed = src.uTimeElapsed;
    dst->dtFixpoint = src.dt_fixpoint;
    dst->totalGameTimeElapsed = src.uTotalTimeElapsed;
}

void reconstruct(const Timer_MM7 &src, Timer *dst) {
    dst->bReady = src.ready;
    dst->bPaused = src.paused;
    dst->bTackGameTime = src.tackGameTime;
    dst->uStartTime = src.startTime;
    dst->uStopTime = src.stopTime;
    dst->uGameTimeStart = src.gameTimeStart;
    dst->uTimeElapsed = src.timeElapsed;
    dst->dt_fixpoint = src.dtFixpoint;
    dst->uTotalTimeElapsed = src.totalGameTimeElapsed;
}

void snapshot(const NPCData &src, NPCData_MM7 *dst) {
    memzero(dst);

    dst->name = !src.pName.empty();
    dst->portraitId = src.uPortraitID;
    dst->flags = std::to_underlying(src.uFlags);
    dst->fame = src.fame;
    dst->rep = src.rep;
    dst->location2d = std::to_underlying(src.Location2D);
    dst->profession = std::to_underlying(src.profession);
    dst->greet = src.greet;
    dst->joins = src.is_joinable;
    dst->field_24 = src.field_24;
    dst->evt_A = src.dialogue_1_evt_id;
    dst->evt_B = src.dialogue_2_evt_id;
    dst->evt_C = src.dialogue_3_evt_id;
    dst->evt_D = src.dialogue_4_evt_id;
    dst->evt_E = src.dialogue_5_evt_id;
    dst->evt_F = src.dialogue_6_evt_id;
    dst->sex = std::to_underlying(src.uSex);
    dst->hasUsedAbility = src.bHasUsedTheAbility;
    dst->newsTopic = src.news_topic;
}

void reconstruct(const NPCData_MM7 &src, NPCData *dst) {
    dst->pName = src.name ? "Dummy" : "";
    dst->uPortraitID = src.portraitId;
    dst->uFlags = NpcFlags(src.flags);
    dst->fame = src.fame;
    dst->rep = src.rep;
    dst->Location2D = static_cast<HouseId>(src.location2d);
    dst->profession = static_cast<NPCProf>(src.profession);
    dst->greet = src.greet;
    dst->is_joinable = src.joins;
    dst->field_24 = src.field_24;
    dst->dialogue_1_evt_id = src.evt_A;
    dst->dialogue_2_evt_id = src.evt_B;
    dst->dialogue_3_evt_id = src.evt_C;
    dst->dialogue_4_evt_id = src.evt_D;
    dst->dialogue_5_evt_id = src.evt_E;
    dst->dialogue_6_evt_id = src.evt_F;
    dst->uSex = static_cast<CharacterSex>(src.sex);
    dst->bHasUsedTheAbility = src.hasUsedAbility;
    dst->news_topic = src.newsTopic;
}

void snapshot(const ActiveOverlay &src, ActiveOverlay_MM7 *dst) {
    memzero(dst);

    dst->indexToOverlayList = src.indexToOverlayList;
    dst->spriteFrameTime = src.spriteFrameTime;
    dst->animLength = src.animLength;
    dst->screenSpaceX = src.screenSpaceX;
    dst->screenSpaceY = src.screenSpaceY;
    dst->pid = src.pid.packed();
    dst->projSize = src.projSize;
    dst->fpDamageMod = src.fpDamageMod;
}

void reconstruct(const ActiveOverlay_MM7 &src, ActiveOverlay *dst) {
    memzero(dst);

    dst->indexToOverlayList = src.indexToOverlayList;
    dst->spriteFrameTime = src.spriteFrameTime;
    dst->animLength = src.animLength;
    dst->screenSpaceX = src.screenSpaceX;
    dst->screenSpaceY = src.screenSpaceY;
    dst->pid = Pid::fromPacked(src.pid);
    dst->projSize = src.projSize;
    dst->fpDamageMod = src.fpDamageMod;
}

void snapshot(const ActiveOverlayList &src, ActiveOverlayList_MM7 *dst) {
    memzero(dst);

    dst->redraw = true;
    snapshot(src.pOverlays, &dst->overlays);
}

void reconstruct(const ActiveOverlayList_MM7 &src, ActiveOverlayList *dst) {
    reconstruct(src.overlays, &dst->pOverlays);
}

void snapshot(const SpellBuff &src, SpellBuff_MM7 *dst) {
    memzero(dst);

    dst->expireTime = src.expireTime.value;
    dst->power = src.power;
    dst->skillMastery = std::to_underlying(src.skillMastery);
    dst->overlayId = src.overlayID;
    dst->caster = src.caster;
    dst->flags = src.isGMBuff;
}

void reconstruct(const SpellBuff_MM7 &src, SpellBuff *dst) {
    dst->expireTime.value = src.expireTime;
    dst->power = src.power;
    dst->skillMastery = static_cast<CharacterSkillMastery>(src.skillMastery);
    dst->overlayID = src.overlayId;
    dst->caster = src.caster;
    dst->isGMBuff = src.flags;
}

void snapshot(const ItemGen &src, ItemGen_MM7 *dst) {
    memzero(dst);

    dst->itemID = std::to_underlying(src.uItemID);
    if (isPotion(src.uItemID)) {
        dst->attributeEnchantmentOrPotionPower = src.potionPower;
    } else if (src.attributeEnchantment) {
        dst->attributeEnchantmentOrPotionPower = std::to_underlying(*src.attributeEnchantment) + 1;
    } else {
        dst->attributeEnchantmentOrPotionPower = 0;
    }
    dst->enchantmentStrength = src.m_enchantmentStrength;
    if (isGold(src.uItemID)) {
        dst->specialEnchantmentOrGoldAmount = src.goldAmount;
    } else {
        dst->specialEnchantmentOrGoldAmount = std::to_underlying(src.special_enchantment);
    }
    dst->numCharges = src.uNumCharges;
    dst->attributes = std::to_underlying(src.uAttributes);
    dst->bodyAnchor = std::to_underlying(src.uBodyAnchor);
    dst->maxCharges = src.uMaxCharges;
    dst->holderPlayer = src.uHolderPlayer;
    dst->placedInChest = src.placedInChest;
    dst->expireTime = src.uExpireTime.value;
}

void reconstruct(const ItemGen_MM7 &src, ItemGen *dst) {
    dst->uItemID = static_cast<ItemId>(src.itemID);
    if (isPotion(dst->uItemID)) {
        dst->potionPower = src.attributeEnchantmentOrPotionPower;
        dst->attributeEnchantment = {};
    } else if (src.attributeEnchantmentOrPotionPower) {
        dst->potionPower = 0;
        dst->attributeEnchantment = static_cast<CharacterAttributeType>(src.attributeEnchantmentOrPotionPower - 1);
    } else {
        dst->potionPower = 0;
        dst->attributeEnchantment = {};
    }
    dst->m_enchantmentStrength = src.enchantmentStrength;
    if (isGold(dst->uItemID)) {
        dst->goldAmount = src.specialEnchantmentOrGoldAmount;
        dst->special_enchantment = ITEM_ENCHANTMENT_NULL;
    } else {
        dst->goldAmount = 0;
        dst->special_enchantment = static_cast<ITEM_ENCHANTMENT>(src.specialEnchantmentOrGoldAmount);
    }
    dst->uNumCharges = src.numCharges;
    dst->uAttributes = ItemFlags(src.attributes);
    dst->uBodyAnchor = static_cast<ItemSlot>(src.bodyAnchor);
    dst->uMaxCharges = src.maxCharges;
    dst->uHolderPlayer = src.holderPlayer;
    dst->placedInChest = src.placedInChest;
    dst->uExpireTime.value = src.expireTime;
}

void snapshot(const Party &src, Party_MM7 *dst) {
    memzero(dst);

    dst->field_0 = 25; // Vanilla set this to 25, so we're doing the same just in case.
    dst->partyHeight = src.height;
    dst->defaultPartyHeight = src.height;
    dst->eyeLevel = src.eyeLevel;
    dst->defaultEyeLevel = src.eyeLevel;
    dst->radius = src.radius;
    dst->yawGranularity = src._yawGranularity;
    dst->walkSpeed = src.walkSpeed;
    dst->yawRotationSpeed = src._yawRotationSpeed;
    dst->jumpStrength = src.jump_strength;
    dst->timePlayed = src.playing_time.value;
    dst->lastRegenerationTime = src.last_regenerated.value;

    snapshot(src.PartyTimes.bountyHuntNextGenTime, &dst->partyTimes.bountyHuntingNextGenerationTime);
    dst->partyTimes.bountyHuntingNextGenerationTimeUnused.fill(0);

    // Initially was one array but was splitted in two to simplify access with first element as zero
    // because it is corresponding to invalid house ID
    dst->partyTimes.shopsNextGenerationTime0 = 0;
    snapshot(src.PartyTimes.shopNextRefreshTime, &dst->partyTimes.shopsNextGenerationTime);
    snapshot(src.PartyTimes.guildNextRefreshTime, &dst->partyTimes.guildsNextGenerationTime);

    dst->partyTimes.shopBanTime0 = 0;
    snapshot(src.PartyTimes.shopBanTimes, &dst->partyTimes.shopBanTimes);
    snapshot(src.PartyTimes.CounterEventValues, &dst->partyTimes.counterEventValues);
    snapshot(src.PartyTimes.HistoryEventTimes, &dst->partyTimes.historyEventTimes);
    snapshot(src.PartyTimes._s_times, &dst->partyTimes.someOtherTimes);

    dst->position = src.pos;
    dst->viewYaw = src._viewYaw;
    dst->viewPitch = src._viewPitch;
    dst->prevPosition = src.lastPos;
    dst->viewPrevYaw = src._viewPrevYaw;
    dst->viewPrevPitch = src._viewPrevPitch;
    dst->prevEyeLevel = src.lastEyeLevel;
    dst->fallSpeed = src.speed.z;
    dst->savedFlightZ = src.sPartySavedFlightZ;
    dst->waterLavaTimer = src._6FC_water_lava_timer;
    dst->fallStartZ = src.uFallStartZ;
    dst->flying = src.bFlying;
    dst->field_708 = 15; // Vanilla set this to 15, so we're doing the same just in case.
    dst->hirelingScrollPosition = src.hirelingScrollPosition;
    dst->field_70A = src.cNonHireFollowers;
    dst->currentYear = src.uCurrentYear;
    dst->currentMonth = src.uCurrentMonth;
    dst->currentMonthWeek = src.uCurrentMonthWeek;
    dst->currentDayOfMonth = src.uCurrentDayOfMonth;
    dst->currentHour = src.uCurrentHour;
    dst->currentMinute = src.uCurrentMinute;
    dst->currentTimeSecond = src.uCurrentTimeSecond;
    dst->numFoodRations = src.GetFood();
    dst->numGold = src.GetGold();
    dst->numGoldInBank = src.uNumGoldInBank;
    dst->numDeaths = src.uNumDeaths;
    dst->numPrisonTerms = src.uNumPrisonTerms;
    dst->numBountiesCollected = src.uNumBountiesCollected;

    snapshot(src.monster_id_for_hunting, &dst->monsterIdForHunting);
    snapshot(src.monster_for_hunting_killed, &dst->monsterForHuntingKilled, tags::convert<bool, int16_t>);

    dst->daysPlayedWithoutRest = src.days_played_without_rest;

    snapshot(src._questBits, &dst->questBits, tags::reverseBits);
    snapshot(src.pArcomageWins, &dst->arcomageWins);

    dst->field_7B5_in_arena_quest = src.field_7B5_in_arena_quest;
    dst->numArenaWins = src.uNumArenaWins;

    snapshot(src.pIsArtifactFound, &dst->isArtifactFound);
    snapshot(src._autonoteBits, &dst->autonoteBits, tags::reverseBits);

    dst->numArcomageWins = src.uNumArcomageWins;
    dst->numArcomageLoses = src.uNumArcomageLoses;
    dst->turnBasedModeOn = src.bTurnBasedModeOn;
    dst->flags2 = std::to_underlying(src.uFlags2);

    uint align = 0;
    if (src.alignment == PartyAlignment::PartyAlignment_Evil) align = 2;
    if (src.alignment == PartyAlignment::PartyAlignment_Neutral) align = 1;
    dst->alignment = align;

    snapshot(src.pPartyBuffs, &dst->partyBuffs);
    snapshot(src.pCharacters, &dst->players);
    snapshot(src.pHirelings, &dst->hirelings);

    snapshot(src.pPickedItem, &dst->pickedItem);

    dst->flags = std::to_underlying(src.uFlags);

    dst->standartItemsInShop0.fill({});
    snapshot(src.standartItemsInShops, &dst->standartItemsInShops);
    dst->specialItemsInShop0.fill({});
    snapshot(src.specialItemsInShops, &dst->specialItemsInShops);
    snapshot(src.spellBooksInGuilds, &dst->spellBooksInGuilds);

    snapshot(src.pHireling1Name, &dst->hireling1Name);
    snapshot(src.pHireling2Name, &dst->hireling2Name);

    dst->armageddonTimer = src.armageddon_timer;
    dst->armageddonDamage = src.armageddonDamage;

    snapshot(src.pTurnBasedCharacterRecoveryTimes, &dst->turnBasedPlayerRecoveryTimes);
    snapshot(src.InTheShopFlags, &dst->inTheShopFlags);

    dst->fine = src.uFine;
}

void reconstruct(const Party_MM7 &src, Party *dst) {
    dst->height = src.partyHeight;
    dst->eyeLevel = src.eyeLevel;
    dst->radius = src.radius;
    dst->_yawGranularity = src.yawGranularity;
    dst->walkSpeed = src.walkSpeed;
    dst->_yawRotationSpeed = src.yawRotationSpeed;
    dst->jump_strength = src.jumpStrength;
    dst->playing_time.value = src.timePlayed;
    dst->last_regenerated.value = src.lastRegenerationTime;

    reconstruct(src.partyTimes.bountyHuntingNextGenerationTime, &dst->PartyTimes.bountyHuntNextGenTime);
    reconstruct(src.partyTimes.shopsNextGenerationTime, &dst->PartyTimes.shopNextRefreshTime);
    reconstruct(src.partyTimes.guildsNextGenerationTime, &dst->PartyTimes.guildNextRefreshTime);
    reconstruct(src.partyTimes.shopBanTimes, &dst->PartyTimes.shopBanTimes);
    reconstruct(src.partyTimes.counterEventValues, &dst->PartyTimes.CounterEventValues);
    reconstruct(src.partyTimes.historyEventTimes, &dst->PartyTimes.HistoryEventTimes);
    reconstruct(src.partyTimes.someOtherTimes, &dst->PartyTimes._s_times);

    dst->pos = src.position;
    dst->_viewYaw = src.viewYaw;
    dst->_viewPitch = src.viewPitch;
    dst->lastPos = src.prevPosition;
    dst->_viewPrevYaw = src.viewPrevYaw;
    dst->_viewPrevPitch = src.viewPrevPitch;
    dst->lastEyeLevel = src.prevEyeLevel;
    dst->speed = Vec3f(0, 0, src.fallSpeed);
    dst->sPartySavedFlightZ = src.savedFlightZ;
    dst->_6FC_water_lava_timer = src.waterLavaTimer;
    dst->uFallStartZ = src.fallStartZ;
    dst->bFlying = src.flying;
    dst->hirelingScrollPosition = src.hirelingScrollPosition;
    dst->cNonHireFollowers = src.field_70A;
    dst->uCurrentYear = src.currentYear;
    dst->uCurrentMonth = src.currentMonth;
    dst->uCurrentMonthWeek = src.currentMonthWeek;
    dst->uCurrentDayOfMonth = src.currentDayOfMonth;
    dst->uCurrentHour = src.currentHour;
    dst->uCurrentMinute = src.currentMinute;
    dst->uCurrentTimeSecond = src.currentTimeSecond;
    dst->uNumFoodRations = src.numFoodRations;
    dst->uNumGold = src.numGold;
    dst->uNumGoldInBank = src.numGoldInBank;
    dst->uNumDeaths = src.numDeaths;
    dst->uNumPrisonTerms = src.numPrisonTerms;
    dst->uNumBountiesCollected = src.numBountiesCollected;

    reconstruct(src.monsterIdForHunting, &dst->monster_id_for_hunting);
    reconstruct(src.monsterForHuntingKilled, &dst->monster_for_hunting_killed, tags::convert<int16_t, bool>);

    dst->days_played_without_rest = src.daysPlayedWithoutRest;

    reconstruct(src.questBits, &dst->_questBits, tags::reverseBits);
    reconstruct(src.arcomageWins, &dst->pArcomageWins);

    dst->field_7B5_in_arena_quest = src.field_7B5_in_arena_quest;
    dst->uNumArenaWins = src.numArenaWins;

    reconstruct(src.isArtifactFound, &dst->pIsArtifactFound);
    reconstruct(src.autonoteBits, &dst->_autonoteBits, tags::reverseBits);

    dst->uNumArcomageWins = src.numArcomageWins;
    dst->uNumArcomageLoses = src.numArcomageLoses;
    dst->bTurnBasedModeOn = src.turnBasedModeOn;
    dst->uFlags2 = static_cast<PARTY_FLAGS_2>(src.flags2);

    switch (src.alignment) {
        case 0:
            dst->alignment = PartyAlignment::PartyAlignment_Good;
            break;
        case 1:
            dst->alignment = PartyAlignment::PartyAlignment_Neutral;
            break;
        case 2:
            dst->alignment = PartyAlignment::PartyAlignment_Evil;
            break;
        default:
            assert(false);
    }

    reconstruct(src.partyBuffs, &dst->pPartyBuffs);
    reconstruct(src.players, &dst->pCharacters);
    reconstruct(src.hirelings, &dst->pHirelings);

    reconstruct(src.pickedItem, &dst->pPickedItem);

    dst->uFlags = static_cast<PARTY_FLAGS_1>(src.flags);

    reconstruct(src.standartItemsInShops, &dst->standartItemsInShops);
    reconstruct(src.specialItemsInShops, &dst->specialItemsInShops);
    reconstruct(src.spellBooksInGuilds, &dst->spellBooksInGuilds);

    reconstruct(src.hireling1Name, &dst->pHireling1Name);
    reconstruct(src.hireling2Name, &dst->pHireling2Name);

    dst->armageddon_timer = src.armageddonTimer;
    dst->armageddonDamage = src.armageddonDamage;

    reconstruct(src.turnBasedPlayerRecoveryTimes, &dst->pTurnBasedCharacterRecoveryTimes);
    reconstruct(src.inTheShopFlags, &dst->InTheShopFlags);

    dst->uFine = src.fine;
}

void snapshot(const Character &src, Player_MM7 *dst) {
    memzero(dst);

    for (unsigned int i = 0; i < 20; ++i)
        dst->conditions[i] = src.conditions.Get(static_cast<Condition>(i)).value;

    dst->experience = src.experience;

    snapshot(src.name, &dst->name);

    dst->sex = std::to_underlying(src.uSex);
    dst->classType = std::to_underlying(src.classType);
    dst->currentFace = src.uCurrentFace;
    dst->might = src.uMight;
    dst->mightBonus = src.uMightBonus;
    dst->intelligence = src.uIntelligence;
    dst->intelligenceBonus = src.uIntelligenceBonus;
    dst->personality = src.uPersonality;
    dst->personalityBonus = src.uPersonalityBonus;
    dst->endurance = src.uEndurance;
    dst->enduranceBonus = src.uEnduranceBonus;
    dst->speed = src.uSpeed;
    dst->speedBonus = src.uSpeedBonus;
    dst->accuracy = src.uAccuracy;
    dst->accuracyBonus = src.uAccuracyBonus;
    dst->luck = src.uLuck;
    dst->luckBonus = src.uLuckBonus;
    dst->acModifier = src.sACModifier;
    dst->level = src.uLevel;
    dst->levelModifier = src.sLevelModifier;
    dst->ageModifier = src.sAgeModifier;
    dst->field_E0 = src.field_E0;
    dst->field_E4 = src.field_E4;
    dst->field_E8 = src.field_E8;
    dst->field_EC = src.field_EC;
    dst->field_F0 = src.field_F0;
    dst->field_F4 = src.field_F4;
    dst->field_F8 = src.field_F8;
    dst->field_FC = src.field_FC;
    dst->field_100 = src.field_100;
    dst->field_104 = src.field_104;

    snapshot(src.pActiveSkills, &dst->activeSkills, tags::segment<CHARACTER_SKILL_FIRST_VISIBLE, CHARACTER_SKILL_LAST_VISIBLE>);
    snapshot(src._achievedAwardsBits, &dst->achievedAwardsBits, tags::reverseBits);
    snapshot(src.spellbook.bHaveSpell, &dst->spellbook.haveSpell);

    dst->pureLuckUsed = src.pure_luck_used;
    dst->pureSpeedUsed = src.pure_speed_used;
    dst->pureIntellectUsed = src.pure_intellect_used;
    dst->pureEnduranceUsed = src.pure_endurance_used;
    dst->purePersonalityUsed = src.pure_personality_used;
    dst->pureAccuracyUsed = src.pure_accuracy_used;
    dst->pureMightUsed = src.pure_might_used;

    snapshot(src.pOwnItems, &dst->ownItems);
    snapshot(src.pInventoryMatrix, &dst->inventoryMatrix);

    dst->resFireBase = src.sResFireBase;
    dst->resAirBase = src.sResAirBase;
    dst->resWaterBase = src.sResWaterBase;
    dst->resEarthBase = src.sResEarthBase;
    dst->resPhysicalBase = src.sResPhysicalBase;
    dst->resMagicBase = src.sResMagicBase;
    dst->resSpiritBase = src.sResSpiritBase;
    dst->resMindBase = src.sResMindBase;
    dst->resBodyBase = src.sResBodyBase;
    dst->resLightBase = src.sResLightBase;
    dst->resDarkBase = src.sResDarkBase;
    dst->resFireBonus = src.sResFireBonus;
    dst->resAirBonus = src.sResAirBonus;
    dst->resWaterBonus = src.sResWaterBonus;
    dst->resEarthBonus = src.sResEarthBonus;
    dst->resPhysicalBonus = src.sResPhysicalBonus;
    dst->resMagicBonus = src.sResMagicBonus;
    dst->resSpiritBonus = src.sResSpiritBonus;
    dst->resMindBonus = src.sResMindBonus;
    dst->resBodyBonus = src.sResBodyBonus;
    dst->resLightBonus = src.sResLightBonus;
    dst->resDarkBonus = src.sResDarkBonus;

    snapshot(src.pCharacterBuffs, &dst->playerBuffs);

    dst->voiceId = src.uVoiceID;
    dst->prevVoiceId = src.uPrevVoiceID;
    dst->prevFace = src.uPrevFace;
    dst->timeToRecovery = src.timeToRecovery;
    dst->skillPoints = src.uSkillPoints;
    dst->health = src.health;
    dst->mana = src.mana;
    dst->birthYear = src.uBirthYear;

    snapshot(src.pEquipment.pIndices, &dst->equipment.indices);

    dst->lastOpenedSpellbookPage = std::to_underlying(src.lastOpenedSpellbookPage);
    dst->quickSpell = std::to_underlying(src.uQuickSpell);

    snapshot(src._characterEventBits, &dst->playerEventBits, tags::reverseBits);

    dst->someAttackBonus = src._some_attack_bonus;
    dst->meleeDmgBonus = src._melee_dmg_bonus;
    dst->rangedAttackBonus = src._ranged_atk_bonus;
    dst->rangedDmgBonus = src._ranged_dmg_bonus;
    dst->fullHealthBonus = src.uFullHealthBonus;
    dst->healthRelated = src._health_related;
    dst->fullManaBonus = src.uFullManaBonus;
    dst->manaRelated = src._mana_related;
    dst->expression = std::to_underlying(src.expression);
    dst->expressionTimePassed = src.uExpressionTimePassed;
    dst->expressionTimeLength = src.uExpressionTimeLength;
    dst->field_1AA2 = src.uExpressionImageIndex;
    dst->_expression21_animtime = src._expression21_animtime;
    dst->_expression21_frameset = src._expression21_frameset;

    for (unsigned int i = 0; i < 5; ++i) {
        if (i >= src.vBeacons.size()) {
            continue;
        }
        dst->installedBeacons[i].beaconTime = src.vBeacons[i].uBeaconTime.value;
        dst->installedBeacons[i].partyPosX = src.vBeacons[i]._partyPos.x;
        dst->installedBeacons[i].partyPosY = src.vBeacons[i]._partyPos.y;
        dst->installedBeacons[i].partyPosZ = src.vBeacons[i]._partyPos.z;
        dst->installedBeacons[i].partyViewYaw = src.vBeacons[i]._partyViewYaw;
        dst->installedBeacons[i].partyViewPitch = src.vBeacons[i]._partyViewPitch;
        dst->installedBeacons[i].mapIndexInGamesLod = valueOr(gamesLodIndexByMapId, src.vBeacons[i].mapId, -1);
    }

    dst->numDivineInterventionCasts = src.uNumDivineInterventionCastsThisDay;
    dst->numArmageddonCasts = src.uNumArmageddonCasts;
    dst->numFireSpikeCasts = src.uNumFireSpikeCasts;
}

void reconstruct(const Player_MM7 &src, Character *dst) {
    for (unsigned int i = 0; i < 20; ++i)
        dst->conditions.Set(static_cast<Condition>(i), GameTime(src.conditions[i]));

    dst->experience = src.experience;

    reconstruct(src.name, &dst->name);

    switch (src.sex) {
    case 0:
        dst->uSex = SEX_MALE;
        break;
    case 1:
        dst->uSex = SEX_FEMALE;
        break;
    default:
        assert(false);
    }

    switch (src.classType) {
    case 0:
        dst->classType = CHARACTER_CLASS_KNIGHT;
        break;
    case 1:
        dst->classType = CHARACTER_CLASS_CAVALIER;
        break;
    case 2:
        dst->classType = CHARACTER_CLASS_CHAMPION;
        break;
    case 3:
        dst->classType = CHARACTER_CLASS_BLACK_KNIGHT;
        break;
    case 4:
        dst->classType = CHARACTER_CLASS_THIEF;
        break;
    case 5:
        dst->classType = CHARACTER_CLASS_ROGUE;
        break;
    case 6:
        dst->classType = CHARACTER_CLASS_SPY;
        break;
    case 7:
        dst->classType = CHARACTER_CLASS_ASSASSIN;
        break;
    case 8:
        dst->classType = CHARACTER_CLASS_MONK;
        break;
    case 9:
        dst->classType = CHARACTER_CLASS_INITIATE;
        break;
    case 10:
        dst->classType = CHARACTER_CLASS_MASTER;
        break;
    case 11:
        dst->classType = CHARACTER_CLASS_NINJA;
        break;
    case 12:
        dst->classType = CHARACTER_CLASS_PALADIN;
        break;
    case 13:
        dst->classType = CHARACTER_CLASS_CRUSADER;
        break;
    case 14:
        dst->classType = CHARACTER_CLASS_HERO;
        break;
    case 15:
        dst->classType = CHARACTER_CLASS_VILLIAN;
        break;
    case 16:
        dst->classType = CHARACTER_CLASS_ARCHER;
        break;
    case 17:
        dst->classType = CHARACTER_CLASS_WARRIOR_MAGE;
        break;
    case 18:
        dst->classType = CHARACTER_CLASS_MASTER_ARCHER;
        break;
    case 19:
        dst->classType = CHARACTER_CLASS_SNIPER;
        break;
    case 20:
        dst->classType = CHARACTER_CLASS_RANGER;
        break;
    case 21:
        dst->classType = CHARACTER_CLASS_HUNTER;
        break;
    case 22:
        dst->classType = CHARACTER_CLASS_RANGER_LORD;
        break;
    case 23:
        dst->classType = CHARACTER_CLASS_BOUNTY_HUNTER;
        break;
    case 24:
        dst->classType = CHARACTER_CLASS_CLERIC;
        break;
    case 25:
        dst->classType = CHARACTER_CLASS_PRIEST;
        break;
    case 26:
        dst->classType = CHARACTER_CLASS_PRIEST_OF_SUN;
        break;
    case 27:
        dst->classType = CHARACTER_CLASS_PRIEST_OF_MOON;
        break;
    case 28:
        dst->classType = CHARACTER_CLASS_DRUID;
        break;
    case 29:
        dst->classType = CHARACTER_CLASS_GREAT_DRUID;
        break;
    case 30:
        dst->classType = CHARACTER_CLASS_ARCH_DRUID;
        break;
    case 31:
        dst->classType = CHARACTER_CLASS_WARLOCK;
        break;
    case 32:
        dst->classType = CHARACTER_CLASS_SORCERER;
        break;
    case 33:
        dst->classType = CHARACTER_CLASS_WIZARD;
        break;
    case 34:
        dst->classType = CHARACTER_CLASS_ARCHAMGE;
        break;
    case 35:
        dst->classType = CHARACTER_CLASS_LICH;
        break;
    default:
        assert(false);
    }

    dst->uCurrentFace = src.currentFace;
    dst->uMight = src.might;
    dst->uMightBonus = src.mightBonus;
    dst->uIntelligence = src.intelligence;
    dst->uIntelligenceBonus = src.intelligenceBonus;
    dst->uPersonality = src.personality;
    dst->uPersonalityBonus = src.personalityBonus;
    dst->uEndurance = src.endurance;
    dst->uEnduranceBonus = src.enduranceBonus;
    dst->uSpeed = src.speed;
    dst->uSpeedBonus = src.speedBonus;
    dst->uAccuracy = src.accuracy;
    dst->uAccuracyBonus = src.accuracyBonus;
    dst->uLuck = src.luck;
    dst->uLuckBonus = src.luckBonus;
    dst->sACModifier = src.acModifier;
    dst->uLevel = src.level;
    dst->sLevelModifier = src.levelModifier;
    dst->sAgeModifier = src.ageModifier;
    dst->field_E0 = src.field_E0;
    dst->field_E4 = src.field_E4;
    dst->field_E8 = src.field_E8;
    dst->field_EC = src.field_EC;
    dst->field_F0 = src.field_F0;
    dst->field_F4 = src.field_F4;
    dst->field_F8 = src.field_F8;
    dst->field_FC = src.field_FC;
    dst->field_100 = src.field_100;
    dst->field_104 = src.field_104;

    reconstruct(src.activeSkills, &dst->pActiveSkills, tags::segment<CHARACTER_SKILL_FIRST_VISIBLE, CHARACTER_SKILL_LAST_VISIBLE>);
    reconstruct(src.achievedAwardsBits, &dst->_achievedAwardsBits, tags::reverseBits);
    reconstruct(src.spellbook.haveSpell, &dst->spellbook.bHaveSpell);

    dst->pure_luck_used = src.pureLuckUsed;
    dst->pure_speed_used = src.pureSpeedUsed;
    dst->pure_intellect_used = src.pureIntellectUsed;
    dst->pure_endurance_used = src.pureEnduranceUsed;
    dst->pure_personality_used = src.purePersonalityUsed;
    dst->pure_accuracy_used = src.pureAccuracyUsed;
    dst->pure_might_used = src.pureMightUsed;

    reconstruct(src.ownItems, &dst->pOwnItems);
    reconstruct(src.inventoryMatrix, &dst->pInventoryMatrix);

    dst->sResFireBase = src.resFireBase;
    dst->sResAirBase = src.resAirBase;
    dst->sResWaterBase = src.resWaterBase;
    dst->sResEarthBase = src.resEarthBase;
    dst->sResPhysicalBase = src.resPhysicalBase;
    dst->sResMagicBase = src.resMagicBase;
    dst->sResSpiritBase = src.resSpiritBase;
    dst->sResMindBase = src.resMindBase;
    dst->sResBodyBase = src.resBodyBase;
    dst->sResLightBase = src.resLightBase;
    dst->sResDarkBase = src.resDarkBase;
    dst->sResFireBonus = src.resFireBonus;
    dst->sResAirBonus = src.resAirBonus;
    dst->sResWaterBonus = src.resWaterBonus;
    dst->sResEarthBonus = src.resEarthBonus;
    dst->sResPhysicalBonus = src.resPhysicalBonus;
    dst->sResMagicBonus = src.resMagicBonus;
    dst->sResSpiritBonus = src.resSpiritBonus;
    dst->sResMindBonus = src.resMindBonus;
    dst->sResBodyBonus = src.resBodyBonus;
    dst->sResLightBonus = src.resLightBonus;
    dst->sResDarkBonus = src.resDarkBonus;

    reconstruct(src.playerBuffs, &dst->pCharacterBuffs);

    dst->uVoiceID = src.voiceId;
    dst->uPrevVoiceID = src.prevVoiceId;
    dst->uPrevFace = src.prevFace;
    dst->timeToRecovery = src.timeToRecovery;
    dst->uSkillPoints = src.skillPoints;
    dst->health = src.health;
    dst->mana = src.mana;
    dst->uBirthYear = src.birthYear;

    reconstruct(src.equipment.indices, &dst->pEquipment.pIndices);

    dst->lastOpenedSpellbookPage = static_cast<MagicSchool>(src.lastOpenedSpellbookPage);
    dst->uQuickSpell = static_cast<SpellId>(src.quickSpell);

    reconstruct(src.playerEventBits, &dst->_characterEventBits, tags::reverseBits);

    dst->_some_attack_bonus = src.someAttackBonus;
    dst->_melee_dmg_bonus = src.meleeDmgBonus;
    dst->_ranged_atk_bonus = src.rangedAttackBonus;
    dst->_ranged_dmg_bonus = src.rangedDmgBonus;
    dst->uFullHealthBonus = src.fullHealthBonus;
    dst->_health_related = src.healthRelated;
    dst->uFullManaBonus = src.fullManaBonus;
    dst->_mana_related = src.manaRelated;
    dst->expression = static_cast<CharacterExpressionID>(src.expression);
    dst->uExpressionTimePassed = src.expressionTimePassed;
    dst->uExpressionTimeLength = src.expressionTimeLength;
    dst->uExpressionImageIndex = src.field_1AA2;
    dst->_expression21_animtime = src._expression21_animtime;
    dst->_expression21_frameset = src._expression21_frameset;

    for (int z = 0; z < dst->vBeacons.size(); z++)
        dst->vBeacons[z].image->Release();
    dst->vBeacons.clear();

    for (unsigned int i = 0; i < 5; ++i) {
        if (src.installedBeacons[i].beaconTime != 0) {
            LloydBeacon beacon;
            beacon.uBeaconTime = GameTime(src.installedBeacons[i].beaconTime);
            beacon._partyPos.x = src.installedBeacons[i].partyPosX;
            beacon._partyPos.y = src.installedBeacons[i].partyPosY;
            beacon._partyPos.z = src.installedBeacons[i].partyPosZ;
            beacon._partyViewYaw = src.installedBeacons[i].partyViewYaw;
            beacon._partyViewPitch = src.installedBeacons[i].partyViewPitch;
            beacon.mapId = valueOr(mapIdByGamesLodIndex, src.installedBeacons[i].mapIndexInGamesLod, MAP_INVALID);
            dst->vBeacons.push_back(beacon);
        }
    }

    dst->uNumDivineInterventionCastsThisDay = src.numDivineInterventionCasts;
    dst->uNumArmageddonCasts = src.numArmageddonCasts;
    dst->uNumFireSpikeCasts = src.numFireSpikeCasts;
}

void snapshot(const Icon &src, IconFrame_MM7 *dst) {
    memzero(dst);

    snapshot(src.GetAnimationName(), &dst->animationName);
    dst->animLength = src.GetAnimLength();

    snapshot(src.pTextureName, &dst->textureName);
    dst->animTime = src.GetAnimTime();
    dst->flags = src.uFlags;
}

void reconstruct(const IconFrame_MM7 &src, Icon *dst) {
    std::string name;
    reconstruct(src.animationName, &name);
    dst->SetAnimationName(name);
    dst->SetAnimLength(8 * src.animLength);

    reconstruct(src.textureName, &dst->pTextureName);
    dst->SetAnimTime(src.animTime);
    dst->uFlags = src.flags;
}

void snapshot(const UIAnimation &src, UIAnimation_MM7 *dst) {
    memzero(dst);

    /* 000 */ dst->iconId = src.icon->id;
    /* 004 */ dst->animTime = src.uAnimTime;
    /* 006 */ dst->animLength = src.uAnimLength;
    /* 008 */ dst->x = src.x;
    /* 00A */ dst->y = src.y;
}

void reconstruct(const UIAnimation_MM7 &src, UIAnimation *dst) {
    dst->icon = pIconsFrameTable->GetIcon(src.iconId);
    ///* 000 */ anim->uIconID = src.uIconID;
    /* 004 */ dst->uAnimTime = src.animTime;
    /* 006 */ dst->uAnimLength = src.animLength;
    /* 008 */ dst->x = src.x;
    /* 00A */ dst->y = src.y;
}

void reconstruct(const MonsterDesc_MM6 &src, MonsterDesc *dst) {
    dst->uMonsterHeight = src.monsterHeight;
    dst->uMonsterRadius = src.monsterRadius;
    dst->uMovementSpeed = src.movementSpeed;
    dst->uToHitRadius = src.toHitRadius;
    dst->sTintColor = colorTable.White;
    dst->pSoundSampleIDs = src.soundSampleIds;
    reconstruct(src.monsterName, &dst->pMonsterName);
    reconstruct(src.spriteNames, &dst->pSpriteNames);
}

void snapshot(const MonsterDesc &src, MonsterDesc_MM7 *dst) {
    memzero(dst);

    dst->monsterHeight = src.uMonsterHeight;
    dst->monsterRadius = src.uMonsterRadius;
    dst->movementSpeed = src.uMovementSpeed;
    dst->toHitRadius = src.uToHitRadius;
    dst->tintColor = src.sTintColor.c32();
    dst->soundSampleIds = src.pSoundSampleIDs;
    snapshot(src.pMonsterName, &dst->monsterName);
    snapshot(src.pSpriteNames, &dst->spriteNames);
    dst->spriteNamesUnused[0].fill('\0');
    dst->spriteNamesUnused[1].fill('\0');
}

void reconstruct(const MonsterDesc_MM7 &src, MonsterDesc *dst) {
    dst->uMonsterHeight = src.monsterHeight;
    dst->uMonsterRadius = src.monsterRadius;
    dst->uMovementSpeed = src.movementSpeed;
    dst->uToHitRadius = src.toHitRadius;
    dst->sTintColor = Color::fromC32(src.tintColor);
    dst->pSoundSampleIDs = src.soundSampleIds;
    reconstruct(src.monsterName, &dst->pMonsterName);
    reconstruct(src.spriteNames, &dst->pSpriteNames);
}

void snapshot(const ActorJob &src, ActorJob_MM7 *dst) {
    memzero(dst);

    snapshot(src.vPos, &dst->pos);
    dst->attributes = src.uAttributes;
    dst->action = src.uAction;
    dst->hour = src.uHour;
    dst->day = src.uDay;
    dst->month = src.uMonth;
}

void reconstruct(const ActorJob_MM7 &src, ActorJob *dst) {
    reconstruct(src.pos, &dst->vPos);
    dst->uAttributes = src.attributes;
    dst->uAction = src.action;
    dst->uHour = src.hour;
    dst->uDay = src.day;
    dst->uMonth = src.month;
}

void snapshot(const Actor &src, Actor_MM7 *dst) {
    memzero(dst);

    snapshot(src.name, &dst->pActorName);

    dst->sNPC_ID = src.npcId;
    dst->uAttributes = std::to_underlying(src.attributes);
    dst->sCurrentHP = src.currentHP;

    dst->pMonsterInfo.level = src.monsterInfo.uLevel;
    dst->pMonsterInfo.treasureDropChance = src.monsterInfo.uTreasureDropChance;
    dst->pMonsterInfo.treasureDiceRolls = src.monsterInfo.uTreasureDiceRolls;
    dst->pMonsterInfo.treasureDiceSides = src.monsterInfo.uTreasureDiceSides;
    dst->pMonsterInfo.treasureLevel = std::to_underlying(src.monsterInfo.uTreasureLevel);
    dst->pMonsterInfo.treasureType = std::to_underlying(src.monsterInfo.uTreasureType);
    dst->pMonsterInfo.flying = src.monsterInfo.uFlying;
    dst->pMonsterInfo.movementType = std::to_underlying(src.monsterInfo.uMovementType);
    dst->pMonsterInfo.aiType = src.monsterInfo.uAIType;
    dst->pMonsterInfo.hostilityType = std::to_underlying(src.monsterInfo.uHostilityType);
    dst->pMonsterInfo.specialAttackType = std::to_underlying(src.monsterInfo.uSpecialAttackType);
    dst->pMonsterInfo.specialAttackLevel = src.monsterInfo.uSpecialAttackLevel;
    dst->pMonsterInfo.attack1Type = std::to_underlying(src.monsterInfo.uAttack1Type);
    dst->pMonsterInfo.attack1DamageDiceRolls = src.monsterInfo.uAttack1DamageDiceRolls;
    dst->pMonsterInfo.attack1DamageDiceSides = src.monsterInfo.uAttack1DamageDiceSides;
    dst->pMonsterInfo.attack1DamageBonus = src.monsterInfo.uAttack1DamageBonus;
    dst->pMonsterInfo.missileAttack1Type = src.monsterInfo.uMissleAttack1Type;
    dst->pMonsterInfo.attack2Chance = src.monsterInfo.uAttack2Chance;
    dst->pMonsterInfo.attack2Type = std::to_underlying(src.monsterInfo.uAttack2Type);
    dst->pMonsterInfo.attack2DamageDiceRolls = src.monsterInfo.uAttack2DamageDiceRolls;
    dst->pMonsterInfo.attack2DamageDiceSides = src.monsterInfo.uAttack2DamageDiceSides;
    dst->pMonsterInfo.attack2DamageBonus = src.monsterInfo.uAttack2DamageBonus;
    dst->pMonsterInfo.missileAttack2Type = src.monsterInfo.uMissleAttack2Type;
    dst->pMonsterInfo.spell1UseChance = src.monsterInfo.uSpell1UseChance;
    dst->pMonsterInfo.spell1Id = std::to_underlying(src.monsterInfo.uSpell1ID);
    dst->pMonsterInfo.spell2UseChance = src.monsterInfo.uSpell2UseChance;
    dst->pMonsterInfo.spell2Id = std::to_underlying(src.monsterInfo.uSpell2ID);
    dst->pMonsterInfo.resFire = src.monsterInfo.uResFire;
    dst->pMonsterInfo.resAir = src.monsterInfo.uResAir;
    dst->pMonsterInfo.resWater = src.monsterInfo.uResWater;
    dst->pMonsterInfo.resEarth = src.monsterInfo.uResEarth;
    dst->pMonsterInfo.resMind = src.monsterInfo.uResMind;
    dst->pMonsterInfo.resSpirit = src.monsterInfo.uResSpirit;
    dst->pMonsterInfo.resBody = src.monsterInfo.uResBody;
    dst->pMonsterInfo.resLight = src.monsterInfo.uResLight;
    dst->pMonsterInfo.resDark = src.monsterInfo.uResDark;
    dst->pMonsterInfo.resPhysical = src.monsterInfo.uResPhysical;
    dst->pMonsterInfo.specialAbilityType = std::to_underlying(src.monsterInfo.uSpecialAbilityType);
    dst->pMonsterInfo.specialAbilityDamageDiceRolls = src.monsterInfo.uSpecialAbilityDamageDiceRolls;
    dst->pMonsterInfo.specialAbilityDamageDiceSides = src.monsterInfo.uSpecialAbilityDamageDiceSides;
    dst->pMonsterInfo.specialAbilityDamageDiceBonus = src.monsterInfo.uSpecialAbilityDamageDiceBonus;
    dst->pMonsterInfo.numCharactersAttackedPerSpecialAbility = src.monsterInfo.uNumCharactersAttackedPerSpecialAbility;
    dst->pMonsterInfo.id = std::to_underlying(src.monsterInfo.uID);
    dst->pMonsterInfo.bloodSplatOnDeath = src.monsterInfo.bBloodSplatOnDeath;
    snapshot(src.monsterInfo.uSpellSkillAndMastery1, &dst->pMonsterInfo.spellSkillAndMastery1);
    snapshot(src.monsterInfo.uSpellSkillAndMastery2, &dst->pMonsterInfo.spellSkillAndMastery2);
    dst->pMonsterInfo.field_3C_some_special_attack = src.monsterInfo.field_3C_some_special_attack;
    dst->pMonsterInfo.field_3E = src.monsterInfo.field_3E;
    dst->pMonsterInfo.hp = src.monsterInfo.uHP;
    dst->pMonsterInfo.ac = src.monsterInfo.uAC;
    dst->pMonsterInfo.exp = src.monsterInfo.uExp;
    dst->pMonsterInfo.baseSpeed = src.monsterInfo.uBaseSpeed;
    dst->pMonsterInfo.recoveryTime = src.monsterInfo.uRecoveryTime;
    dst->pMonsterInfo.attackPreference = src.monsterInfo.uAttackPreference;
    dst->word_000084_range_attack = src.word_000084_range_attack;
    dst->word_000086_some_monster_id = std::to_underlying(src.word_000086_some_monster_id);  // base monster class monsterlist id
    dst->uActorRadius = src.radius;
    dst->uActorHeight = src.height;
    dst->uMovementSpeed = src.moveSpeed;
    snapshot(src.pos, &dst->vPosition);
    snapshot(src.speed, &dst->vVelocity);
    dst->uYawAngle = src.yawAngle;
    dst->uPitchAngle = src.pitchAngle;
    dst->uSectorID = src.sectorId;
    dst->uCurrentActionLength = src.currentActionLength;
    snapshot(src.initialPosition, &dst->vInitialPosition);
    snapshot(src.guardingPosition, &dst->vGuardingPosition);
    dst->uTetherDistance = src.tetherDistance;
    dst->uAIState = std::to_underlying(src.aiState);
    dst->uCurrentActionAnimation = std::to_underlying(src.currentActionAnimation);
    dst->uCarriedItemID = std::to_underlying(src.carriedItemId);
    dst->uCurrentActionTime = src.currentActionTime;

    snapshot(src.spriteIds, &dst->pSpriteIDs);
    snapshot(src.soundSampleIds, &dst->pSoundSampleIDs);
    snapshot(src.buffs, &dst->pActorBuffs);
    snapshot(src.items, &dst->ActorHasItems);

    dst->uGroup = src.group;
    dst->uAlly = std::to_underlying(src.ally);

    snapshot(src.scheduledJobs, &dst->pScheduledJobs);

    dst->uSummonerID = src.summonerId.packed();
    dst->uLastCharacterIDToHit = src.lastCharacterIdToHit.packed();
    dst->dword_000334_unique_name = src.dword_000334_unique_name;
}

void reconstruct(const Actor_MM7 &src, Actor *dst) {
    reconstruct(src.pActorName, &dst->name);
    dst->npcId = src.sNPC_ID;
    dst->attributes = ActorAttributes(src.uAttributes);
    dst->currentHP = src.sCurrentHP;

    dst->monsterInfo.uLevel = src.pMonsterInfo.level;
    dst->monsterInfo.uTreasureDropChance = src.pMonsterInfo.treasureDropChance;
    dst->monsterInfo.uTreasureDiceRolls = src.pMonsterInfo.treasureDiceRolls;
    dst->monsterInfo.uTreasureDiceSides = src.pMonsterInfo.treasureDiceSides;
    dst->monsterInfo.uTreasureLevel = static_cast<ItemTreasureLevel>(src.pMonsterInfo.treasureLevel);
    dst->monsterInfo.uTreasureType = static_cast<RandomItemType>(src.pMonsterInfo.treasureType);
    dst->monsterInfo.uFlying = src.pMonsterInfo.flying;
    dst->monsterInfo.uMovementType = static_cast<MONSTER_MOVEMENT_TYPE>(src.pMonsterInfo.movementType);
    dst->monsterInfo.uAIType = src.pMonsterInfo.aiType;
    dst->monsterInfo.uHostilityType = static_cast<MonsterHostility>(src.pMonsterInfo.hostilityType);
    dst->monsterInfo.uSpecialAttackType = static_cast<SPECIAL_ATTACK_TYPE>(src.pMonsterInfo.specialAttackType);
    dst->monsterInfo.uSpecialAttackLevel = src.pMonsterInfo.specialAttackLevel;
    dst->monsterInfo.uAttack1Type = static_cast<DAMAGE_TYPE>(src.pMonsterInfo.attack1Type);
    dst->monsterInfo.uAttack1DamageDiceRolls = src.pMonsterInfo.attack1DamageDiceRolls;
    dst->monsterInfo.uAttack1DamageDiceSides = src.pMonsterInfo.attack1DamageDiceSides;
    dst->monsterInfo.uAttack1DamageBonus = src.pMonsterInfo.attack1DamageBonus;
    dst->monsterInfo.uMissleAttack1Type = src.pMonsterInfo.missileAttack1Type;
    dst->monsterInfo.uAttack2Chance = src.pMonsterInfo.attack2Chance;
    dst->monsterInfo.uAttack2Type = static_cast<DAMAGE_TYPE>(src.pMonsterInfo.attack2Type);
    dst->monsterInfo.uAttack2DamageDiceRolls = src.pMonsterInfo.attack2DamageDiceRolls;
    dst->monsterInfo.uAttack2DamageDiceSides = src.pMonsterInfo.attack2DamageDiceSides;
    dst->monsterInfo.uAttack2DamageBonus = src.pMonsterInfo.attack2DamageBonus;
    dst->monsterInfo.uMissleAttack2Type = src.pMonsterInfo.missileAttack2Type;
    dst->monsterInfo.uSpell1UseChance = src.pMonsterInfo.spell1UseChance;
    dst->monsterInfo.uSpell1ID = static_cast<SpellId>(src.pMonsterInfo.spell1Id);
    dst->monsterInfo.uSpell2UseChance = src.pMonsterInfo.spell2UseChance;
    dst->monsterInfo.uSpell2ID = static_cast<SpellId>(src.pMonsterInfo.spell2Id);
    dst->monsterInfo.uResFire = src.pMonsterInfo.resFire;
    dst->monsterInfo.uResAir = src.pMonsterInfo.resAir;
    dst->monsterInfo.uResWater = src.pMonsterInfo.resWater;
    dst->monsterInfo.uResEarth = src.pMonsterInfo.resEarth;
    dst->monsterInfo.uResMind = src.pMonsterInfo.resMind;
    dst->monsterInfo.uResSpirit = src.pMonsterInfo.resSpirit;
    dst->monsterInfo.uResBody = src.pMonsterInfo.resBody;
    dst->monsterInfo.uResLight = src.pMonsterInfo.resLight;
    dst->monsterInfo.uResDark = src.pMonsterInfo.resDark;
    dst->monsterInfo.uResPhysical = src.pMonsterInfo.resPhysical;
    dst->monsterInfo.uSpecialAbilityType = static_cast<MONSTER_SPECIAL_ABILITY_TYPE>(src.pMonsterInfo.specialAbilityType);
    dst->monsterInfo.uSpecialAbilityDamageDiceRolls = src.pMonsterInfo.specialAbilityDamageDiceRolls;
    dst->monsterInfo.uSpecialAbilityDamageDiceSides = src.pMonsterInfo.specialAbilityDamageDiceSides;
    dst->monsterInfo.uSpecialAbilityDamageDiceBonus = src.pMonsterInfo.specialAbilityDamageDiceBonus;
    dst->monsterInfo.uNumCharactersAttackedPerSpecialAbility = src.pMonsterInfo.numCharactersAttackedPerSpecialAbility;
    dst->monsterInfo.uID = static_cast<MonsterId>(src.pMonsterInfo.id);
    dst->monsterInfo.bBloodSplatOnDeath = src.pMonsterInfo.bloodSplatOnDeath;
    reconstruct(src.pMonsterInfo.spellSkillAndMastery1, &dst->monsterInfo.uSpellSkillAndMastery1);
    reconstruct(src.pMonsterInfo.spellSkillAndMastery2, &dst->monsterInfo.uSpellSkillAndMastery2);
    dst->monsterInfo.field_3C_some_special_attack = src.pMonsterInfo.field_3C_some_special_attack;
    dst->monsterInfo.field_3E = src.pMonsterInfo.field_3E;
    dst->monsterInfo.uHP = src.pMonsterInfo.hp;
    dst->monsterInfo.uAC = src.pMonsterInfo.ac;
    dst->monsterInfo.uExp = src.pMonsterInfo.exp;
    dst->monsterInfo.uBaseSpeed = src.pMonsterInfo.baseSpeed;
    dst->monsterInfo.uRecoveryTime = src.pMonsterInfo.recoveryTime;
    dst->monsterInfo.uAttackPreference = src.pMonsterInfo.attackPreference;
    dst->word_000084_range_attack = src.word_000084_range_attack;
    dst->word_000086_some_monster_id = static_cast<MonsterId>(src.word_000086_some_monster_id);  // base monster class monsterlist id
    dst->radius = src.uActorRadius;
    dst->height = src.uActorHeight;
    dst->moveSpeed = src.uMovementSpeed;
    reconstruct(src.vPosition, &dst->pos);
    reconstruct(src.vVelocity, &dst->speed);
    dst->yawAngle = src.uYawAngle;
    dst->pitchAngle = src.uPitchAngle;
    dst->sectorId = src.uSectorID;
    dst->currentActionLength = src.uCurrentActionLength;
    reconstruct(src.vInitialPosition, &dst->initialPosition);
    reconstruct(src.vGuardingPosition, &dst->guardingPosition);
    dst->tetherDistance = src.uTetherDistance;
    dst->aiState = static_cast<AIState>(src.uAIState);
    dst->currentActionAnimation = static_cast<ActorAnimation>(src.uCurrentActionAnimation);
    dst->carriedItemId = ItemId(src.uCarriedItemID);
    dst->currentActionTime = src.uCurrentActionTime;

    reconstruct(src.pSpriteIDs, &dst->spriteIds);
    reconstruct(src.pSoundSampleIDs, &dst->soundSampleIds);
    reconstruct(src.pActorBuffs, &dst->buffs);
    reconstruct(src.ActorHasItems, &dst->items);

    dst->group = src.uGroup;
    dst->ally = static_cast<MonsterType>(src.uAlly);

    reconstruct(src.pScheduledJobs, &dst->scheduledJobs);

    dst->summonerId = Pid::fromPacked(src.uSummonerID);
    dst->lastCharacterIdToHit = Pid::fromPacked(src.uLastCharacterIDToHit);
    dst->dword_000334_unique_name = src.dword_000334_unique_name;
}

void snapshot(const BLVDoor &src, BLVDoor_MM7 *dst) {
    memzero(dst);

    dst->uAttributes = std::to_underlying(src.uAttributes);
    dst->uDoorID = src.uDoorID;
    dst->uTimeSinceTriggered = src.uTimeSinceTriggered;
    dst->vDirection = src.vDirection;
    dst->uMoveLength = src.uMoveLength;
    dst->uOpenSpeed = src.uOpenSpeed;
    dst->uCloseSpeed = src.uCloseSpeed;
    dst->uNumVertices = src.uNumVertices;
    dst->uNumFaces = src.uNumFaces;
    dst->uNumSectors = src.uNumSectors;
    dst->uNumOffsets = src.uNumOffsets;
    dst->uState = std::to_underlying(src.uState);
}

void reconstruct(const BLVDoor_MM7 &src, BLVDoor *dst) {
    dst->uAttributes = static_cast<DoorAttributes>(src.uAttributes);
    dst->uDoorID = src.uDoorID;
    dst->uTimeSinceTriggered = src.uTimeSinceTriggered;
    dst->vDirection = src.vDirection;
    dst->uMoveLength = src.uMoveLength;
    dst->uOpenSpeed = src.uOpenSpeed;
    dst->uCloseSpeed = src.uCloseSpeed;
    dst->uNumVertices = src.uNumVertices;
    dst->uNumFaces = src.uNumFaces;
    dst->uNumSectors = src.uNumSectors;
    dst->uNumOffsets = src.uNumOffsets;
    dst->uState = static_cast<BLVDoor::State>(src.uState);
}

void snapshot(const BLVSector &src, BLVSector_MM7 *dst) {
    memzero(dst);

    dst->field_0 = src.field_0;
    dst->uNumFloors = src.uNumFloors;
    dst->uNumWalls = src.uNumWalls;
    dst->uNumCeilings = src.uNumCeilings;
    dst->uNumFluids = src.uNumFluids;
    dst->uNumPortals = src.uNumPortals;
    dst->uNumFaces = src.uNumFaces;
    dst->uNumNonBSPFaces = src.uNumNonBSPFaces;
    dst->uNumCylinderFaces = src.uNumCylinderFaces;
    dst->pCylinderFaces = src.pCylinderFaces;
    dst->uNumCogs = src.uNumCogs;
    dst->uNumDecorations = src.uNumDecorations;
    dst->uNumMarkers = src.uNumMarkers;
    dst->uNumLights = src.uNumLights;
    dst->uWaterLevel = src.uWaterLevel;
    dst->uMistLevel = src.uMistLevel;
    dst->uLightDistanceMultiplier = src.uLightDistanceMultiplier;
    dst->uMinAmbientLightLevel = src.uMinAmbientLightLevel;
    dst->uFirstBSPNode = src.uFirstBSPNode;
    dst->exit_tag = src.exit_tag;
    snapshot(src.pBounding, &dst->pBounding);
}

void reconstruct(const BLVSector_MM7 &src, BLVSector *dst) {
    dst->field_0 = src.field_0;
    dst->uNumFloors = src.uNumFloors;
    dst->uNumWalls = src.uNumWalls;
    dst->uNumCeilings = src.uNumCeilings;
    dst->uNumFluids = src.uNumFluids;
    dst->uNumPortals = src.uNumPortals;
    dst->uNumFaces = src.uNumFaces;
    dst->uNumNonBSPFaces = src.uNumNonBSPFaces;
    dst->uNumCylinderFaces = src.uNumCylinderFaces;
    dst->pCylinderFaces = src.pCylinderFaces;
    dst->uNumCogs = src.uNumCogs;
    dst->uNumDecorations = src.uNumDecorations;
    dst->uNumMarkers = src.uNumMarkers;
    dst->uNumLights = src.uNumLights;
    dst->uWaterLevel = src.uWaterLevel;
    dst->uMistLevel = src.uMistLevel;
    dst->uLightDistanceMultiplier = src.uLightDistanceMultiplier;
    dst->uMinAmbientLightLevel = src.uMinAmbientLightLevel;
    dst->uFirstBSPNode = src.uFirstBSPNode;
    dst->exit_tag = src.exit_tag;
    reconstruct(src.pBounding, &dst->pBounding);
}

void snapshot(const GUICharMetric &src, GUICharMetric_MM7 *dst) {
    memzero(dst);

    dst->uLeftSpacing = src.uLeftSpacing;
    dst->uWidth = src.uWidth;
    dst->uRightSpacing = src.uRightSpacing;
}

void reconstruct(const GUICharMetric_MM7 &src, GUICharMetric *dst) {
    dst->uLeftSpacing = src.uLeftSpacing;
    dst->uWidth = src.uWidth;
    dst->uRightSpacing = src.uRightSpacing;
}

void snapshot(const FontData &src, FontData_MM7 *dst) {
    memzero(dst);

    dst->cFirstChar = src.cFirstChar;
    dst->cLastChar = src.cLastChar;
    dst->uFontHeight = src.uFontHeight;
    dst->palletes_count = src.palletes_count;

    snapshot(src.pMetrics, &dst->pMetrics);
    snapshot(src.font_pixels_offset, &dst->font_pixels_offset);

    std::copy(src.pFontData.begin(), src.pFontData.end(), dst->pFontData);
}

void reconstruct(const FontData_MM7 &src, size_t size, FontData *dst) {
    dst->cFirstChar = src.cFirstChar;
    dst->cLastChar = src.cLastChar;
    dst->uFontHeight = src.uFontHeight;
    dst->palletes_count = src.palletes_count;

    reconstruct(src.pMetrics, &dst->pMetrics);
    reconstruct(src.font_pixels_offset, &dst->font_pixels_offset);

    dst->pFontData.assign(src.pFontData, &src.pFontData[size - 4128]);
}

void reconstruct(const ODMFace_MM7 &src, ODMFace *dst) {
    reconstruct(src.facePlane, &dst->facePlane);
    dst->zCalc.init(dst->facePlane);
    dst->uAttributes = FaceAttributes(src.attributes);
    dst->pVertexIDs = src.pVertexIDs;
    dst->pTextureUIDs = src.pTextureUIDs;
    dst->pTextureVIDs = src.pTextureVIDs;
    dst->resource = nullptr;
    dst->sTextureDeltaU = src.sTextureDeltaU;
    dst->sTextureDeltaV = src.sTextureDeltaV;
    reconstruct(src.pBoundingBox, &dst->pBoundingBox);
    dst->sCogNumber = src.sCogNumber;
    dst->sCogTriggeredID = src.sCogTriggeredID;
    dst->sCogTriggerType = src.sCogTriggerType;
    dst->uNumVertices = src.uNumVertices;
    dst->uPolygonType = static_cast<PolygonType>(src.uPolygonType);
    dst->uShadeType = src.uShadeType;
    dst->bVisible = src.bVisible;
}

void reconstruct(const SpawnPoint_MM7 &src, SpawnPoint *dst) {
    dst->vPosition = src.vPosition;
    dst->uRadius = src.uRadius;
    dst->uKind = static_cast<ObjectType>(src.uKind);
    if (dst->uKind == OBJECT_Actor) {
        dst->uItemIndex = ITEM_TREASURE_LEVEL_INVALID;
        dst->uMonsterIndex = src.uIndex;
    } else {
        assert(dst->uKind == OBJECT_Item);
        dst->uItemIndex = static_cast<ItemTreasureLevel>(src.uIndex);
        dst->uMonsterIndex = 0;
    }
    dst->uAttributes = src.uAttributes;
    dst->uGroup = src.uGroup;
}

void snapshot(const SpriteObject &src, SpriteObject_MM7 *dst) {
    memzero(dst);

    dst->uType = std::to_underlying(src.uType);
    dst->uObjectDescID = src.uObjectDescID;
    dst->vPosition = src.vPosition;
    snapshot(src.vVelocity, &dst->vVelocity);
    dst->uFacing = src.uFacing;
    dst->uSoundID = src.uSoundID;
    dst->uAttributes = std::to_underlying(src.uAttributes);
    dst->uSectorID = src.uSectorID;
    dst->uSpriteFrameID = src.uSpriteFrameID;
    dst->tempLifetime = src.tempLifetime;
    dst->field_22_glow_radius_multiplier = src.field_22_glow_radius_multiplier;
    snapshot(src.containing_item, &dst->containing_item);
    dst->uSpellID = std::to_underlying(src.uSpellID);
    dst->spell_level = src.spell_level;
    dst->spell_skill = std::to_underlying(src.spell_skill);
    dst->field_54 = src.field_54;
    dst->spell_caster_pid = src.spell_caster_pid.packed();
    dst->spell_target_pid = src.spell_target_pid.packed();
    dst->field_60_distance_related_prolly_lod = src.field_60_distance_related_prolly_lod;
    dst->spellCasterAbility = std::to_underlying(src.spellCasterAbility);
    dst->initialPosition = src.initialPosition;
}

void reconstruct(const SpriteObject_MM7 &src, SpriteObject *dst) {
    dst->uType = static_cast<SPRITE_OBJECT_TYPE>(src.uType);
    dst->uObjectDescID = src.uObjectDescID;
    dst->vPosition = src.vPosition;
    reconstruct(src.vVelocity, &dst->vVelocity);
    dst->uFacing = src.uFacing;
    dst->uSoundID = src.uSoundID;
    dst->uAttributes = SpriteAttributes(src.uAttributes);
    dst->uSectorID = src.uSectorID;
    dst->uSpriteFrameID = src.uSpriteFrameID;
    dst->tempLifetime = src.tempLifetime;
    dst->field_22_glow_radius_multiplier = src.field_22_glow_radius_multiplier;
    reconstruct(src.containing_item, &dst->containing_item);
    dst->uSpellID = static_cast<SpellId>(src.uSpellID);
    dst->spell_level = src.spell_level;
    dst->spell_skill = static_cast<CharacterSkillMastery>(src.spell_skill);
    dst->field_54 = src.field_54;
    dst->spell_caster_pid = Pid::fromPacked(src.spell_caster_pid);
    dst->spell_target_pid = Pid::fromPacked(src.spell_target_pid);
    dst->field_60_distance_related_prolly_lod = src.field_60_distance_related_prolly_lod;
    dst->spellCasterAbility = static_cast<ABILITY_INDEX>(src.spellCasterAbility);
    dst->initialPosition = src.initialPosition;
}

void reconstruct(const ChestDesc_MM7 &src, ChestDesc *dst) {
    reconstruct(src.pName, &dst->sName);
    dst->uWidth = src.uWidth;
    dst->uHeight = src.uHeight;
    dst->uTextureID = src.uTextureID;
}

void reconstruct(const DecorationDesc_MM6 &src, DecorationDesc *dst) {
    reconstruct(src.pName, &dst->pName);
    reconstruct(src.field_20, &dst->field_20);
    dst->uType = src.uType;
    dst->uDecorationHeight = src.uDecorationHeight;
    dst->uRadius = src.uRadius;
    dst->uLightRadius = src.uLightRadius;
    dst->uSpriteID = src.uSpriteID;
    dst->uFlags = DecorationDescFlags(src.uFlags);
    dst->uSoundID = src.uSoundID;

    dst->uColoredLight.r = 255;
    dst->uColoredLight.g = 255;
    dst->uColoredLight.b = 255;
    dst->uColoredLight.a = 255;
}

void reconstruct(const DecorationDesc_MM7 &src, DecorationDesc *dst) {
    reconstruct(static_cast<const DecorationDesc_MM6 &>(src), dst);

    dst->uColoredLight.r = src.uColoredLightRed;
    dst->uColoredLight.g = src.uColoredLightGreen;
    dst->uColoredLight.b = src.uColoredLightBlue;
    dst->uColoredLight.a = 255;
}

void snapshot(const Chest &src, Chest_MM7 *dst) {
    memzero(dst);

    dst->uChestBitmapID = src.uChestBitmapID;
    dst->uFlags = std::to_underlying(src.uFlags);
    snapshot(src.igChestItems, &dst->igChestItems);
    snapshot(src.pInventoryIndices, &dst->pInventoryIndices);
}

void reconstruct(const Chest_MM7 &src, Chest *dst) {
    dst->uChestBitmapID = src.uChestBitmapID;
    dst->uFlags = ChestFlags(src.uFlags);
    reconstruct(src.igChestItems, &dst->igChestItems);
    reconstruct(src.pInventoryIndices, &dst->pInventoryIndices);

    // fix placedInChest field for old saves
    int chestArea = dst->pInventoryIndices.size();
    for (int item = 0; item < chestArea; item++) {
        if (dst->igChestItems[item].uItemID == ITEM_NULL) {
            continue;
        }
        for (int position = 0; position < chestArea; position++) {
            if (dst->pInventoryIndices[position] == item + 1) {
                dst->igChestItems[item].placedInChest = true;
                break;
            }
        }
    }
}

void reconstruct(const BLVLight_MM7 &src, BLVLight *dst) {
    reconstruct(src.vPosition, &dst->vPosition);
    dst->uRadius = src.uRadius;
    dst->uRed = src.uRed;
    dst->uGreen = src.uGreen;
    dst->uBlue = src.uBlue;
    dst->uType = src.uType;
    dst->uAtributes = src.uAtributes;
    dst->uBrightness = src.uBrightness;
}

void reconstruct(const OverlayDesc_MM7 &src, OverlayDesc *dst) {
    dst->uOverlayID = src.uOverlayID;
    dst->uOverlayType = src.uOverlayType;
    dst->uSpriteFramesetID = src.uSpriteFramesetID;
    dst->spriteFramesetGroup = src.spriteFramesetGroup;
}

void reconstruct(const PlayerFrame_MM7 &src, PlayerFrame *dst) {
    dst->expression = static_cast<CharacterExpressionID>(src.expression);
    dst->uTextureID = src.uTextureID;
    dst->uAnimTime = src.uAnimTime;
    dst->uAnimLength = src.uAnimLength;
    dst->uFlags = src.uFlags;
}

void reconstruct(const LevelDecoration_MM7 &src, LevelDecoration *dst) {
    dst->uDecorationDescID = src.uDecorationDescID;
    dst->uFlags = LevelDecorationFlags(src.uFlags);
    dst->vPosition = src.vPosition;
    dst->_yawAngle = src._yawAngle;
    dst->uCog = src.uCog;
    dst->uEventID = src.uEventID;
    dst->uTriggerRange = src.uTriggerRange;
    dst->field_1A = src.field_1A;
    dst->eventVarId = src.eventVarId - 75; // Was changed because all current usages are without this 75 shift
}

void reconstruct(const BLVFaceExtra_MM7 &src, BLVFaceExtra *dst) {
    dst->face_id = src.face_id;
    dst->uAdditionalBitmapID = src.uAdditionalBitmapID;
    dst->sTextureDeltaU = src.sTextureDeltaU;
    dst->sTextureDeltaV = src.sTextureDeltaV;
    dst->sCogNumber = src.sCogNumber;
    dst->uEventID = src.uEventID;
}

void reconstruct(const BSPNode_MM7 &src, BSPNode *dst) {
    dst->uFront = src.uFront;
    dst->uBack = src.uBack;
    dst->uBSPFaceIDOffset = src.uBSPFaceIDOffset;
    dst->uNumBSPFaces = src.uNumBSPFaces;
}

void reconstruct(const BLVMapOutline_MM7 &src, BLVMapOutline *dst) {
    dst->uVertex1ID = src.uVertex1ID;
    dst->uVertex2ID = src.uVertex2ID;
    dst->uFace1ID = src.uFace1ID;
    dst->uFace2ID = src.uFace2ID;
    dst->sZ = src.sZ;
    dst->uFlags = src.uFlags;
}

void reconstruct(const ObjectDesc_MM6 &src, ObjectDesc *dst) {
    reconstruct(src.name, &dst->name);
    dst->uObjectID = static_cast<SPRITE_OBJECT_TYPE>(src.uObjectID);
    dst->uRadius = src.uRadius;
    dst->uHeight = src.uHeight;
    dst->uFlags = ObjectDescFlags(src.uFlags);
    dst->uSpriteID = src.uSpriteID;
    dst->uLifetime = src.uLifetime;
    // Note: src.uParticleTrailColor16 is ignored.
    dst->uParticleTrailColor = Color(src.uParticleTrailColorR, src.uParticleTrailColorG, src.uParticleTrailColorB);
    dst->uSpeed = src.uSpeed;
}

void reconstruct(const ObjectDesc_MM7 &src, ObjectDesc *dst) {
    reconstruct(src.name, &dst->name);
    dst->uObjectID = static_cast<SPRITE_OBJECT_TYPE>(src.uObjectID);
    dst->uRadius = src.uRadius;
    dst->uHeight = src.uHeight;
    dst->uFlags = ObjectDescFlags(src.uFlags);
    dst->uSpriteID = src.uSpriteID;
    dst->uLifetime = src.uLifetime;
    // Note: src.uParticleTrailColor32 is ignored.
    dst->uParticleTrailColor = Color(src.uParticleTrailColorR, src.uParticleTrailColorG, src.uParticleTrailColorB);
    dst->uSpeed = src.uSpeed;
}

void snapshot(const LocationTime &src, LocationTime_MM7 *dst) {
    memzero(dst);

    snapshot(src.last_visit, &dst->last_visit);
    snapshot(src.sky_texture_name, &dst->sky_texture_name);
    dst->day_attrib = std::to_underlying(src.day_attrib);
    dst->day_fogrange_1 = src.day_fogrange_1;
    dst->day_fogrange_2 = src.day_fogrange_2;
}

void reconstruct(const LocationTime_MM7 &src, LocationTime *dst) {
    reconstruct(src.last_visit, &dst->last_visit);
    reconstruct(src.sky_texture_name, &dst->sky_texture_name);
    dst->day_attrib = static_cast<MapWeatherFlags>(src.day_attrib);
    dst->day_fogrange_1 = src.day_fogrange_1;
    dst->day_fogrange_2 = src.day_fogrange_2;
}

void reconstruct(const SoundInfo_MM6 &src, SoundInfo *dst) {
    reconstruct(src.pSoundName, &dst->sName);
    dst->uSoundID = src.uSoundID;
    dst->eType = static_cast<SOUND_TYPE>(src.eType);
    dst->uFlags = src.uFlags;
}

void reconstruct(const SoundInfo_MM7 &src, SoundInfo *dst) {
    reconstruct(static_cast<const SoundInfo_MM6 &>(src), dst);
}

void snapshot(const LocationInfo &src, LocationInfo_MM7 *dst) {
    memzero(dst);

    dst->respawnCount = src.respawnCount;
    dst->lastRespawnDay = src.lastRespawnDay;
    dst->reputation = src.reputation;
    dst->alertStatus = src.alertStatus;
}

void reconstruct(const LocationInfo_MM7 &src, LocationInfo *dst) {
    dst->respawnCount = src.respawnCount;
    dst->lastRespawnDay = src.lastRespawnDay;
    dst->reputation = src.reputation;
    dst->alertStatus = src.alertStatus;
}

void snapshot(const PersistentVariables &src, PersistentVariables_MM7 *dst) {
    memzero(dst);

    dst->mapVars = src.mapVars;
    dst->decorVars = src.decorVars;
}

void reconstruct(const PersistentVariables_MM7 &src, PersistentVariables *dst) {
    dst->mapVars = src.mapVars;
    dst->decorVars = src.decorVars;
}

void reconstruct(const OutdoorLocationTileType_MM7 &src, OutdoorLocationTileType *dst) {
    dst->tileset = static_cast<Tileset>(src.tileset);
    dst->uTileID = src.tileId;
}

void snapshot(const SaveGameHeader &src, SaveGameHeader_MM7 *dst) {
    memzero(dst);

    snapshot(src.name, &dst->name);
    snapshot(src.locationName, &dst->locationName);
    snapshot(src.playingTime, &dst->playingTime);
}

void reconstruct(const SaveGameHeader_MM7 &src, SaveGameHeader *dst) {
    reconstruct(src.name, &dst->name);
    reconstruct(src.locationName, &dst->locationName);
    reconstruct(src.playingTime, &dst->playingTime);
    // field_30 is ignored.
}
