#pragma once

#include <cstdint>

#include "Library/Serialization/SerializationFwd.h"

#include "Utility/Flags.h"

#define PARTY_AUTONOTES_BIT__EMERALD_FIRE_FOUNTAIN 2

/**
 * Quest bits, numbered as in MM7's `quests.txt`. MM6 and MM8 give these numbers different meanings.
 */
enum class QuestBit : uint16_t {
    QBIT_INVALID = 0,
    QBIT_EMERALD_ISLAND_RED_POTION_ACTIVE = 1,
    QBIT_EMERALD_ISLAND_SEASHELL_ACTIVE = 2,
    QBIT_EMERALD_ISLAND_LONGBOW_ACTIVE = 3,
    QBIT_EMERALD_ISLAND_FLOOR_TILE_ACTIVE = 4,
    QBIT_EMERALD_ISLAND_LUTE_ACTIVE = 5,
    QBIT_EMERALD_ISLAND_HAT_ACTIVE = 6,
    QBIT_EMERALD_ISLAND_SCAVENGER_HUNT_WON = 7,
    QBIT_EMERALD_ISLAND_RED_POTION_GIVEN = 8,
    QBIT_EMERALD_ISLAND_SEASHELL_GIVEN = 9,
    QBIT_EMERALD_ISLAND_LONGBOW_GIVEN = 10,
    QBIT_EMERALD_ISLAND_FLOOR_TILE_GIVEN = 11,
    QBIT_EMERALD_ISLAND_LUTE_GIVEN = 12,
    QBIT_EMERALD_ISLAND_HAT_GIVEN = 13,
    QBIT_MALWICK_FIREBALL_WAND_ACCEPTED = 14,
    QBIT_EMERALD_ISLAND_SHIP_OFFERED = 15,
    QBIT_EMERALD_ISLAND_MISSING_CONTESTANTS_ACTIVE = 16,
    QBIT_EMERALD_ISLAND_MARGARET_TOUR_OFF = 17,
    QBIT_MARKHAM_VASE_ACTIVE = 18,
    QBIT_WATCHTOWER_6_WEIGHT_ACTIVE = 19,
    QBIT_WATCHTOWER_6_WEIGHT_PLACED = 20,
    QBIT_LADY_CARMINE_ACTIVE = 21,
    QBIT_WROMTHRAX_ACTIVE = 22,
    QBIT_WROMTHRAX_KILLED = 23,
    QBIT_ALICE_HARGREAVES_RESCUE_ACTIVE = 24,
    QBIT_ALICE_HARGREAVES_TAKEN = 25,
    QBIT_ALICE_HARGREAVES_CAPTURE_ACTIVE = 26,
    QBIT_MEDITATION_SPOT_ACTIVE = 27,
    QBIT_HIGH_PRIEST_OF_BAA_ACTIVE = 28,
    QBIT_ASHWAR_NOG_NOGOTH_TOMB_ACTIVE = 29,
    QBIT_PERFECT_BOW_LIGHT_ACTIVE = 30,
    QBIT_RED_DWARF_MINES_LIFT_ACTIVE = 31,
    QBIT_PERFECT_BOW_DARK_ACTIVE = 32,
    QBIT_ARENA_FIVE_WINS_ACTIVE = 33,
    QBIT_HAUNTED_HOUSE_UNDEAD_ACTIVE = 34,
    QBIT_ELVEN_TREASURY_ACTIVE = 35,
    QBIT_CALM_TULAREAN_TREES_ACTIVE = 36,
    QBIT_FAERIE_MOUND_ACTIVE = 37,
    QBIT_TOWN_HALL_BOUNTIES_ACTIVE = 38,
    QBIT_HEART_OF_THE_WOOD_ACTIVE = 39,
    QBIT_TALKED_TO_OLDEST_TREE = 40, // No MM7 script sets it, Lysander Sweet only tests it.
    QBIT_HEART_OF_THE_WOOD_RETURNED = 41,
    QBIT_TEMPLE_OF_THE_MOON_ALTAR_ACTIVE = 42,
    QBIT_EVENMORN_MAP_ACTIVE = 43,
    QBIT_TEMPLE_OF_THE_SUN_ALTAR_ACTIVE = 44,
    QBIT_GOLEM_ACTIVE = 45,
    QBIT_GOLEM_ANIMATED = 46,
    QBIT_DIVINE_INTERVENTION_BOOK_ACTIVE = 47,
    QBIT_LICH_JARS_ACTIVE = 48,
    QBIT_STONEHENGES_ACTIVE = 49,
    QBIT_STONEHENGES_VISITED = 50,
    QBIT_EVENMORN_STONEHENGE_VISITED = 51,
    QBIT_TATALIA_STONEHENGE_VISITED = 52,
    QBIT_AVLEE_STONEHENGE_VISITED = 53,
    QBIT_ZOKARR_BONES_ACTIVE = 54,
    QBIT_DRAGON_EGG_ACTIVE = 55,
    QBIT_WATCHTOWER_6_WEIGHT_TAKEN = 56, // No MM7 script sets it, the Spy promotion only tests it.
    QBIT_HIDDEN_TOMB_CODE_ENTERED = 57,
    QBIT_RED_DWARF_MINES_LIFT_SABOTAGED = 58,
    QBIT_ARENA_FIVE_WINS_FINISHED = 59, // Unused.
    QBIT_ELVEN_TREASURY_ROBBED = 60,
    QBIT_TOWN_HALL_BOUNTIES_COLLECTED = 61, // Unused.
    QBIT_TEMPLE_OF_THE_MOON_ALTAR_PURIFIED = 62,
    QBIT_TEMPLE_OF_THE_SUN_ALTAR_DEFILED = 63,
    QBIT_EVENMORN_MAP_GIVEN = 64, // Also unlocks the boat routes to Evenmorn Island.
    QBIT_ZOKARR_BONES_RETURNED = 65,
    QBIT_GOLEM_CHEST_PLACED = 66,
    QBIT_GOLEM_LEFT_LEG_PLACED = 67,
    QBIT_GOLEM_RIGHT_LEG_PLACED = 68,
    QBIT_GOLEM_LEFT_ARM_PLACED = 69,
    QBIT_GOLEM_RIGHT_ARM_PLACED = 70,
    QBIT_GOLEM_HEAD_PLACED = 71,
    QBIT_ABBEY_NORMAL_GOLEM_HEAD_PLACED = 72,
    QBIT_ABBEY_NORMAL_GOLEM_ASSEMBLED = 73,
    QBIT_GOLEM_ASSEMBLED = 74,
    QBIT_CASTLE_HARMONDALE_GOBLINS_ACTIVE = 75,
    QBIT_RED_DWARF_MINES_RESCUE_ACTIVE = 76,
    QBIT_RIVERSTRIDE_PLANS_ACTIVE = 77,
    QBIT_LOREN_STEEL_RESCUE_ACTIVE = 78,
    QBIT_GRYPHONHEART_TRUMPET_ACTIVE = 79,
    QBIT_RIVERSTRIDE_PLANS_GIVEN = 80,
    QBIT_LOREN_STEEL_RESCUED = 81,
    QBIT_FALSE_RIVERSTRIDE_PLANS_GIVEN = 82,
    QBIT_FALSE_LOREN_GIVEN = 83,
    QBIT_GRYPHONHEART_TRUMPET_GIVEN_TO_ERATHIA = 84,
    QBIT_GRYPHONHEART_TRUMPET_GIVEN_TO_AVLEE = 85,
    QBIT_WEAPONS_GIVEN_TO_ERATHIA = 86, // Unused.
    QBIT_WEAPONS_GIVEN_TO_AVLEE = 87, // Unused.
    QBIT_TALKED_TO_CATHERINE = 88,
    QBIT_TALKED_TO_ELF_KING = 89,
    QBIT_FALSE_LOREN_REVEALED = 90,
    QBIT_FALSE_RIVERSTRIDE_PLANS_REVEALED = 91,
    QBIT_RIVERSTRIDE_VAULT_OPENED = 92,
    QBIT_LOREN_STEEL_FREED = 93,
    QBIT_FALSE_RIVERSTRIDE_PLANS_ACTIVE = 94,
    QBIT_FALSE_LOREN_ACTIVE = 95,
    QBIT_CASTLE_HARMONDALE_UPGRADED_LIGHT = 96, // Unused.
    QBIT_CASTLE_HARMONDALE_UPGRADED_DARK = 97, // Unused.
    QBIT_HARMONDALE_REBUILT = 98,
    QBIT_LIGHT_PATH = 99,
    QBIT_DARK_PATH = 100,
    QBIT_WALLS_OF_MIST_ACTIVE = 101,
    QBIT_WALLS_OF_MIST_PASSED = 102,
    QBIT_ALTAR_PIECES_LIGHT_ACTIVE = 103,
    QBIT_XENOFEX_LIGHT_ACTIVE = 104,
    QBIT_XENOFEX_KILLED = 105,
    QBIT_WINE_CELLAR_ACTIVE = 106,
    QBIT_WINE_CELLAR_VAMPIRE_KILLED = 107, // Also set without a kill check by the Vampire Family House exit.
    QBIT_SOUL_JARS_LIGHT_ACTIVE = 108,
    QBIT_TOLBERTI_ASSASSINATION_ACTIVE = 109,
    QBIT_DARK_GUILD_JOINED = 110,
    QBIT_ALTAR_PIECES_DARK_FINISHED = 111,
    QBIT_SOUL_JARS_DARK_FINISHED = 112,
    QBIT_CLANKERS_LAB_FINISHED = 113,
    QBIT_LIGHT_GUILD_JOINED = 114,
    QBIT_ALTAR_PIECES_LIGHT_FINISHED = 115,
    QBIT_WINE_CELLAR_FINISHED = 116,
    QBIT_SOUL_JARS_LIGHT_FINISHED = 117,
    QBIT_ROBERT_THE_WISE_ASSASSINATED = 118,
    QBIT_TOLBERTI_ASSASSINATED = 119,
    QBIT_XENOFEX_QUEST_FINISHED = 120,
    QBIT_OSCILLATION_OVERTHRUSTER_TAKEN = 121,
    QBIT_ALTAR_PIECES_DARK_ACTIVE = 122,
    QBIT_XENOFEX_DARK_ACTIVE = 123,
    QBIT_SOUL_JARS_DARK_ACTIVE = 124,
    QBIT_CLANKERS_LAB_ACTIVE = 125,
    QBIT_CLANKERS_LAB_DEFENSES_DESTROYED = 126,
    QBIT_ROBERT_THE_WISE_ASSASSINATION_ACTIVE = 127,
    QBIT_BREEDING_ZONE_ACTIVE = 128,
    QBIT_BREEDING_ZONE_FINISHED = 129,
    QBIT_OSCILLATION_OVERTHRUSTER_LIGHT_ACTIVE = 130,
    QBIT_OSCILLATION_OVERTHRUSTER_DARK_ACTIVE = 131,
    QBIT_BUTLER_MET = 132,
    QBIT_CASTLE_HARMONDALE_TIMER_STARTED = 133,
    QBIT_ARBITER_MESSENGER_MET = 134,
    QBIT_CASTLE_HARMONDALE_GOBLINS_KILLED = 135,
    QBIT_ESCAPED_EMERALD_ISLE = 136,
    QBIT_GRYPHONHEART_TRUMPET_MESSENGER_MET = 137,
    QBIT_ARMSMASTER_GRANDMASTER_MONSTER_KILLED = 138, // Unused.
    QBIT_WATER_GRANDMASTER_FOUNTAIN_FINISHED = 139, // Unused.
    QBIT_HAUNTED_HOUSE_CLEARED = 140,
    QBIT_MARKHAM_VASE_TAKEN = 141,
    QBIT_HAUNTED_HOUSE_MONSTERS_KILLED = 142, // Unused.
    QBIT_BANDIT_CAVES_CLEARED = 143,
    QBIT_ALICE_HARGREAVES_MET = 144, // Unused.
    QBIT_SORCERY_SCHOOL_MEMBERSHIP_BOUGHT = 145, // Cleared again by a long timer in the School of Sorcery.
    QBIT_CASTLE_HARMONDALE_REPAIR_ACTIVE = 146,
    QBIT_GRYPHONHEART_TRUMPET_GIVEN_TO_ARBITER = 147,
    QBIT_WALLS_OF_MIST_LICH_JARS_TAKEN = 148,
    QBIT_THUNDERFIST_SOUL_JARS_TAKEN = 149,
    QBIT_CASTLE_GLOAMING_SOUL_JARS_TAKEN = 150,
    QBIT_ARCHIBALD_VISIT_ACTIVE = 151,
    QBIT_GAVIN_MAGNUS_VISIT_ACTIVE = 152,
    QBIT_ARBITER_CHOICE_ACTIVE = 153,
    QBIT_SCROLL_OF_WAVES_TAKEN = 154,
    QBIT_LANTERN_OF_LIGHT_ACTIVE = 155,
    QBIT_HALDARS_REMAINS_ACTIVE = 156,
    QBIT_DAVRIKS_SIGNET_RING_ACTIVE = 157,
    QBIT_THRUSH_LETTER_ACTIVE = 158,
    QBIT_PARSONS_QUILL_ACTIVE = 159,
    QBIT_DAVRIKS_SIGNET_RING_TAKEN = 160,
    QBIT_HALDARS_REMAINS_TAKEN = 161,
    QBIT_LANTERN_OF_LIGHT_TAKEN = 162, // Unused.
    QBIT_PERFECT_BOW_TAKEN = 163,
    QBIT_OBELISK_IN_HARMONDALE_FOUND = 164,
    QBIT_OBELISK_IN_ERATHIA_FOUND = 165,
    QBIT_OBELISK_IN_TULAREAN_FOREST_FOUND = 166,
    QBIT_OBELISK_IN_DEYJA_FOUND = 167,
    QBIT_OBELISK_IN_BRACADA_DESERT_FOUND = 168,
    QBIT_OBELISK_IN_CELESTE_FOUND = 169,
    QBIT_OBELISK_IN_THE_PIT_FOUND = 170,
    QBIT_OBELISK_IN_EVENMORN_ISLAND_FOUND = 171,
    QBIT_OBELISK_IN_MOUNT_NIGHON_FOUND = 172,
    QBIT_OBELISK_IN_BARROW_DOWNS_FOUND = 173,
    QBIT_OBELISK_IN_LAND_OF_THE_GIANTS_FOUND = 174,
    QBIT_OBELISK_IN_TATALIA_FOUND = 175,
    QBIT_OBELISK_IN_AVLEE_FOUND = 176,
    QBIT_OBELISK_IN_STONE_CITY_FOUND = 177,
    QBIT_OBELISK_TREASURE_FOUND = 178,
    QBIT_FAERIE_KING_LETTER_ACTIVE = 179,
    QBIT_FAERIE_PIPES_ACTIVE = 180,
    QBIT_MERCENARY_GUILD_VISIT_ACTIVE = 181,
    QBIT_MERCENARY_GUILD_TAPESTRY_ACTIVE = 182,
    QBIT_MERCENARY_GUILD_QUEST_FAILED = 183, // While set, raiders occupy Harmondale and its shops are locked.
    QBIT_CASTLE_HARMONDALE_RAIDERS_KILLED = 184,
    QBIT_HARMONDALE_RAIDERS_KILLED = 185,
    QBIT_STONE_CITY_TROGLODYTES_ACTIVE = 186,
    QBIT_GRIFFINS_ACTIVE = 187,
    QBIT_ERATHIA_GRIFFINS_KILLED = 188,
    QBIT_BRACADA_DESERT_GRIFFINS_KILLED = 189,
    QBIT_MALWICK_QUESTS_FINISHED = 190,
    QBIT_BARROW_IX_KEY_USED = 191, // Opens the sealed doors in Barrows I, VI, VIII, IX and XIII.
    QBIT_BARROW_VII_KEY_USED = 192, // Opens the sealed doors in Barrows II, III, IV, VII and XIV.
    QBIT_BARROW_X_KEY_USED = 193, // Opens the sealed doors in Barrows V, X, XI, XII and XV.
    QBIT_DARRONS_BROTHER_ACTIVE = 194,
    QBIT_SEASONS_STOLE_ACTIVE = 195,
    QBIT_WATCHTOWER_6_BACK_DOOR_USED = 196,
    QBIT_FAERIE_MOUND_ENTERED = 197, // No MM7 script sets it, the Faeries topic only tests it.
    QBIT_ARCHIBALD_MOVED_TO_CLANKERS_LAB = 198,
    QBIT_MERCENARY_GUILD_TAPESTRY_TAKEN = 199,
    QBIT_STATUETTES_ACTIVE = 200,
    QBIT_KNIGHT_STATUETTE_PLACED = 201,
    QBIT_EAGLE_STATUETTE_PLACED = 202,
    QBIT_ANGEL_STATUETTE_PLACED = 203,
    QBIT_PAINTINGS_ACTIVE = 204,
    QBIT_ARCOMAGE_ALL_TAVERNS_ACTIVE = 205,
    QBIT_TOWN_PORTAL_TO_HARMONDALE = 206,
    QBIT_TOWN_PORTAL_TO_ERATHIA = 207,
    QBIT_TOWN_PORTAL_TO_TULAREAN_FOREST = 208,
    QBIT_TOWN_PORTAL_TO_CELESTE = 209,
    QBIT_TOWN_PORTAL_TO_THE_PIT = 210,
    QBIT_TOWN_PORTAL_TO_MOUNT_NIGHON = 211,
    QBIT_ORACLE_RECOVERS_VASE = 212,
    QBIT_ORACLE_RECOVERS_LADY_CARMINES_DAGGER = 213,
    QBIT_ORACLE_RECOVERS_SCROLL_OF_WAVES = 214,
    QBIT_ORACLE_RECOVERS_CIPHER = 215,
    QBIT_ORACLE_RECOVERS_WORN_BELT = 216,
    QBIT_ORACLE_RECOVERS_HEART_OF_THE_WOOD = 217,
    QBIT_ORACLE_RECOVERS_EVENMORN_MAP = 218,
    QBIT_ORACLE_RECOVERS_GOLEM_HEAD = 219,
    QBIT_ORACLE_RECOVERS_ABBEY_NORMAL_GOLEM_HEAD = 220,
    QBIT_ORACLE_RECOVERS_GOLEM_RIGHT_ARM = 221,
    QBIT_ORACLE_RECOVERS_GOLEM_LEFT_ARM = 222,
    QBIT_ORACLE_RECOVERS_GOLEM_RIGHT_LEG = 223,
    QBIT_ORACLE_RECOVERS_GOLEM_LEFT_LEG = 224,
    QBIT_ORACLE_RECOVERS_GOLEM_CHEST = 225,
    QBIT_ORACLE_RECOVERS_DIVINE_INTERVENTION_BOOK = 226,
    QBIT_ORACLE_RECOVERS_DRAGON_EGG = 227,
    QBIT_ORACLE_RECOVERS_ZOKARR_IVS_SKULL = 228,
    QBIT_ORACLE_RECOVERS_LICH_JAR_EMPTY = 229, // No MM7 script sets it.
    QBIT_ORACLE_RECOVERS_ELIXIR = 230,
    QBIT_ORACLE_RECOVERS_CASE_OF_SOUL_JARS = 231,
    QBIT_ORACLE_RECOVERS_ALTAR_PIECE_LIGHT = 232,
    QBIT_ORACLE_RECOVERS_ALTAR_PIECE_DARK = 233,
    QBIT_ORACLE_RECOVERS_CONTROL_CUBE = 234, // No MM7 script clears it, so it stays set after Robert the Wise or Tolberti takes the cube.
    QBIT_ORACLE_RECOVERS_WETSUIT = 235,
    QBIT_ORACLE_RECOVERS_OSCILLATION_OVERTHRUSTER = 236,
    QBIT_ORACLE_RECOVERS_LICH_JAR_FULL = 237, // No MM7 script sets it.
    QBIT_ARCOMAGE_CHAMPION = 238,
    QBIT_DIVINE_INTERVENTION_RETRIEVED = 239,
    QBIT_TALKED_TO_ROLAND = 240, // Clicked Roland Ironfist's cage in Colony Zod and got the key.
    QBIT_ORACLE_RECOVERS_PERFECT_BOW = 241, // No MM7 script sets it.
    QBIT_HIDDEN_TOMB_SARCOPHAGUS_OPENED = 242,
    QBIT_HIGH_PRIEST_OF_BAA_KILLED = 243,
    QBIT_ARCOMAGE_QUEST_FINISHED = 244,
    QBIT_FANFARE = 245, // Set and cleared back to back to play the new quest fanfare.
    QBIT_LAND_OF_THE_GIANTS_ALTAR_USED = 246, // Unlocks the Harmondale altar's teleport to the Land of the Giants.
    QBIT_SMALL_HOUSE_CONTROL_CUBES_GIVEN = 247,
    QBIT_HARMONDALE_HILL_FORT_ENTERED = 248,
    QBIT_LUNIUS_SHADOR_PAID = 249,
    QBIT_ARROWHEAD_CRATE_BOUGHT = 250,
    QBIT_GRIFFIN_FEATHER_CRATE_BOUGHT = 251,
    QBIT_TULAREAN_WOOD_CRATE_BOUGHT = 252,
    QBIT_SAND_CRATE_BOUGHT = 253,
    QBIT_GLASS_BOTTLE_CRATE_BOUGHT = 254,
    QBIT_ENROTHIAN_WINE_CRATE_BOUGHT = 255,
    QBIT_ARROWHEAD_CRATE_EVER_BOUGHT = 256,
    QBIT_GRIFFIN_FEATHER_CRATE_EVER_BOUGHT = 257,
    QBIT_TULAREAN_WOOD_CRATE_EVER_BOUGHT = 258,
    QBIT_SAND_CRATE_EVER_BOUGHT = 259,
    QBIT_GLASS_BOTTLE_CRATE_EVER_BOUGHT = 260,
    QBIT_ENROTHIAN_WINE_CRATE_EVER_BOUGHT = 261,
    QBIT_HARMONDALE_SIGNAL_FIRES_LIT = 262, // Wakes the goblin raiding camp on the next map load.
    QBIT_ARCHIBALD_MET_IN_LAND_OF_THE_GIANTS = 263,
    QBIT_ROLAND_PAINTING_TAKEN = 264,
    QBIT_ARCHIBALD_PAINTING_TAKEN = 265,
    QBIT_ANGEL_STATUE_PAINTING_TAKEN = 266,
    QBIT_HARMONDALE_SOUTH_SIGNAL_FIRE_LIT = 267,
    QBIT_HARMONDALE_NORTH_SIGNAL_FIRE_LIT = 268,
    QBIT_HARMONDALE_WEST_SIGNAL_FIRE_LIT = 269,
    QBIT_ALLIED_GUARDS_ANGERED = 270, // Cleared by a map load at least 720 hours after it was set.
    QBIT_HARMONDALE_FACTION_BANNERS_HUNG = 271,

    QBIT_FIRST = 1,
    QBIT_LAST = 512
};
using enum QuestBit;

enum class PartyFlag : int32_t {
    PARTY_FLAG_0002 = 0x0002, // was force drawing
    PARTY_FLAG_WATER_DAMAGE = 0x0004,
    PARTY_FLAG_AIRBORNE = 0x0008,
    PARTY_FLAG_ALERT_RED = 0x0010,
    PARTY_FLAG_ALERT_YELLOW = 0x0020,
    PARTY_FLAG_ALERT_RED_OR_YELLOW = PARTY_FLAG_ALERT_RED | PARTY_FLAG_ALERT_YELLOW,
    PARTY_FLAG_STANDING_ON_WATER = 0x0080,
    // In vanilla landing flag used to control for no damage landings
    // OE now uses this as a flag for landing from flight
    PARTY_FLAG_LANDING = 0x0100,
    PARTY_FLAG_BURNING = 0x0200,

    // New to OE - flag used to negate landing damage after jumping
    PARTY_FLAG_JUMPING = 0x0400
};
using enum PartyFlag;
MM_DECLARE_FLAGS(PartyFlags, PartyFlag)
MM_DECLARE_OPERATORS_FOR_FLAGS(PartyFlags)

// TODO(captainurist): is there other flag values? Maybe just drop this enum.
enum class PARTY_FLAG_2 : int32_t {
    PARTY_FLAGS_2_RUNNING = 0x2,
};
using enum PARTY_FLAG_2;
MM_DECLARE_FLAGS(PARTY_FLAGS_2, PARTY_FLAG_2)
MM_DECLARE_OPERATORS_FOR_FLAGS(PARTY_FLAGS_2)

enum class PartyBuff {
    PARTY_BUFF_RESIST_AIR = 0,
    PARTY_BUFF_RESIST_BODY = 1,
    PARTY_BUFF_DAY_OF_GODS = 2,
    PARTY_BUFF_DETECT_LIFE = 3,
    PARTY_BUFF_RESIST_EARTH = 4,
    PARTY_BUFF_FEATHER_FALL = 5,
    PARTY_BUFF_RESIST_FIRE = 6,
    PARTY_BUFF_FLY = 7,
    PARTY_BUFF_HASTE = 8,
    PARTY_BUFF_HEROISM = 9,
    PARTY_BUFF_IMMOLATION = 10,
    PARTY_BUFF_INVISIBILITY = 11,
    PARTY_BUFF_RESIST_MIND = 12,
    PARTY_BUFF_PROTECTION_FROM_MAGIC = 13,
    PARTY_BUFF_SHIELD = 14,
    PARTY_BUFF_STONE_SKIN = 15,
    PARTY_BUFF_TORCHLIGHT = 16,
    PARTY_BUFF_RESIST_WATER = 17,
    PARTY_BUFF_WATER_WALK = 18,
    PARTY_BUFF_WIZARD_EYE = 19,

    PARTY_BUFF_FIRST = PARTY_BUFF_RESIST_AIR,
    PARTY_BUFF_LAST = PARTY_BUFF_WIZARD_EYE
};
using enum PartyBuff;

enum class PartyAction : uint32_t {
    PARTY_INVALID = 0,
    PARTY_TurnLeft = 1,
    PARTY_TurnRight = 2,
    PARTY_StrafeLeft = 3,
    PARTY_StrafeRight = 4,
    PARTY_WalkForward = 5,
    PARTY_WalkBackward = 6,
    PARTY_LookUp = 7,
    PARTY_LookDown = 8,
    PARTY_CenterView = 9,
    PARTY_unkA = 10,
    PARTY_unkB = 11,
    PARTY_Jump = 12,
    PARTY_FlyUp = 13,
    PARTY_FlyDown = 14,
    PARTY_Land = 15,
    PARTY_RunForward = 16,
    PARTY_RunBackward = 17,
    PARTY_FastTurnLeft = 18,
    PARTY_FastTurnRight = 19,
    PARTY_UNUSED = 20, // was MouseLook

    PARTY_dword = 0xFFFFFFFF
};
using enum PartyAction;

enum class PartyAlignment : int32_t {
    PartyAlignment_Good = 0,
    PartyAlignment_Neutral = 1,
    PartyAlignment_Evil = 2
};
using enum PartyAlignment;
MM_DECLARE_SERIALIZATION_FUNCTIONS(PartyAlignment);

/**
 * Controls gold receiving mechanics.
 */
enum class GoldReceivePolicy {
    GOLD_RECEIVE_SHARE,          // default behaviour: receive gold and share it with hirelings
    GOLD_RECEIVE_NOSHARE_MSG,    // receive gold without sharing, displays status message
    GOLD_RECEIVE_NOSHARE_SILENT  // receive gold without sharing and status message
};
using enum GoldReceivePolicy;
