#include "Arcomage.h"

ArcomageCard pCards[87]  =  {
    { .pCardName = "Brick Shortage", .card_resource_type = 1, .to_pl_enm_bricks = -8},
    { .pCardName = "Lucky Cache", .slot = 1, .card_resource_type = 1, .field_30 = 1, .to_player_bricks = 2, .to_player_gems = 2},
    { .pCardName = "Friendly Terrain", .slot = 2, .card_resource_type = 1, .needed_bricks = 1, .field_30 = 1, .to_player_wall = 1},
    { .pCardName = "Miners", .slot = 3, .card_resource_type = 1, .needed_bricks = 3, .to_player_quarry_lvl = 1},
    { .pCardName = "Mother Lode", .slot = 4, .card_resource_type = 1, .needed_bricks = 4, .compare_param = ArcomageCompareParam::LESSER_QUARRY, .to_player_quarry_lvl = 2, .to_player_quarry_lvl2 = 1},
    { .pCardName = "Dwarven Miners", .slot = 5, .card_resource_type = 1, .needed_bricks = 7, .to_player_quarry_lvl = 1, .to_player_wall = 4},
    { .pCardName = "Work Overtime", .slot = 6, .card_resource_type = 1, .needed_bricks = 2, .to_player_gems = -6, .to_player_wall = 5},
    { .pCardName = "Copping the Tech", .slot = 7, .card_resource_type = 1, .needed_bricks = 5, .compare_param = ArcomageCompareParam::LESSER_QUARRY, .to_player_quarry_lvl = 99},
    { .pCardName = "Basic Wall", .slot = 8, .card_resource_type = 1, .needed_bricks = 2, .to_player_wall = 3},
    { .pCardName = "Sturdy Wall", .slot = 9, .card_resource_type = 1, .needed_bricks = 3, .to_player_wall = 4},
    { .pCardName = "Innovations", .slot = 10, .card_resource_type = 1, .needed_bricks = 2, .to_player_gems = 4, .to_pl_enm_quarry_lvl = 1},
    { .pCardName = "Foundations", .slot = 11, .card_resource_type = 1, .needed_bricks = 3, .compare_param = ArcomageCompareParam::NO_WALL, .to_player_wall = 6, .to_player_wall2 = 3},
    { .pCardName = "Tremors", .slot = 12, .card_resource_type = 1, .needed_bricks = 7, .field_30 = 1, .to_pl_enm_wall = -5},
    { .pCardName = "Secret Room", .slot = 13, .card_resource_type = 1, .needed_bricks = 8, .field_30 = 1, .to_player_magic_lvl = 1},
    { .pCardName = "Earthquake", .slot = 14, .card_resource_type = 1, .to_pl_enm_quarry_lvl = -1},
    { .pCardName = "Big Wall", .slot = 15, .card_resource_type = 1, .needed_bricks = 5, .to_player_wall = 6},
    { .pCardName = "Collapse!", .slot = 16, .card_resource_type = 1, .needed_bricks = 4, .to_enemy_quarry_lvl = -1},
    { .pCardName = "New Equipment", .slot = 17, .card_resource_type = 1, .needed_bricks = 6, .to_player_quarry_lvl = 2},
    { .pCardName = "Strip Mine", .slot = 18, .card_resource_type = 1, .to_player_quarry_lvl = -1, .to_player_gems = 5, .to_player_wall = 10},
    { .pCardName = "Reinforced Wall", .slot = 19, .card_resource_type = 1, .needed_bricks = 8, .to_player_wall = 8},
    { .pCardName = "Porticulus", .slot = 20, .card_resource_type = 1, .needed_bricks = 9, .to_player_zoo_lvl = 1, .to_player_wall = 5},
    { .pCardName = "Crystal Rocks", .slot = 21, .card_resource_type = 1, .needed_bricks = 9, .to_player_gems = 7, .to_player_wall = 7},
    { .pCardName = "Harmonic Ore", .slot = 22, .card_resource_type = 1, .needed_bricks = 11, .to_player_wall = 6, .to_player_tower = 3},
    { .pCardName = "Mondo Wall", .slot = 23, .card_resource_type = 1, .needed_bricks = 13, .to_player_wall = 12},
    { .pCardName = "Focused Designs", .slot = 24, .card_resource_type = 1, .needed_bricks = 15, .to_player_wall = 8, .to_player_tower = 5},
    { .pCardName = "Great Wall", .slot = 25, .card_resource_type = 1, .needed_bricks = 16, .to_player_wall = 15},
    { .pCardName = "Rock Launcer", .slot = 26, .card_resource_type = 1, .needed_bricks = 18, .to_player_wall = 6, .to_enemy_buildings = -10},
    { .pCardName = "Dragon's Heart", .slot = 27, .card_resource_type = 1, .needed_bricks = 24, .to_player_wall = 20, .to_player_tower = 8},
    { .pCardName = "Quartz", .slot = 30, .card_resource_type = 2, .needed_gems = 1, .field_30 = 1, .to_player_tower = 1},
    { .pCardName = "Smoky Quartz", .slot = 31, .card_resource_type = 2, .needed_gems = 2, .field_30 = 1, .to_enemy_tower = -1},
    { .pCardName = "Amethyst", .slot = 32, .card_resource_type = 2, .needed_gems = 2, .to_player_tower = 3},
    { .pCardName = "Spell Weavers", .slot = 33, .card_resource_type = 2, .needed_gems = 3, .to_player_magic_lvl = 1},
    { .pCardName = "Prism", .slot = 34, .card_resource_type = 2, .needed_gems = 2, .field_30 = 1, .draw_extra_card_count = 1},
    { .pCardName = "Lodestone", .slot = 35, .card_resource_type = 2, .needed_gems = 5, .can_be_discarded = 0, .to_player_tower = 3},
    { .pCardName = "Solar Flare", .slot = 36, .card_resource_type = 2, .needed_gems = 4, .to_player_tower = 2, .to_enemy_tower = -2},
    { .pCardName = "Crystal Matrix", .slot = 37, .card_resource_type = 2, .needed_gems = 6, .to_player_magic_lvl = 1, .to_player_tower = 3, .to_enemy_tower = 1},
    { .pCardName = "Gemstone Flaw", .slot = 38, .card_resource_type = 2, .needed_gems = 2, .to_enemy_tower = -3},
    { .pCardName = "Ruby", .slot = 39, .card_resource_type = 2, .needed_gems = 3, .to_player_tower = 5},
    { .pCardName = "Gem Spear", .slot = 40, .card_resource_type = 2, .needed_gems = 4, .to_enemy_tower = -5},
    { .pCardName = "Power Burn", .slot = 41, .card_resource_type = 2, .needed_gems = 3, .to_player_magic_lvl = 2, .to_player_tower = -5},
    { .pCardName = "Harmonic Vibe", .slot = 42, .card_resource_type = 2, .needed_gems = 7, .to_player_magic_lvl = 1, .to_player_wall = 3, .to_player_tower = 3},
    { .pCardName = "Parity", .slot = 43, .card_resource_type = 2, .needed_gems = 7, .compare_param = ArcomageCompareParam::LESSER_MAGIC, .to_player_magic_lvl = 99, .to_enemy_magic_lvl2 = 99},
    { .pCardName = "Emerald", .slot = 44, .card_resource_type = 2, .needed_gems = 6, .to_player_tower = 8},
    { .pCardName = "Pearl of Wisdom", .slot = 45, .card_resource_type = 2, .needed_gems = 9, .to_player_magic_lvl = 1, .to_player_tower = 5},
    { .pCardName = "Shatter", .slot = 46, .card_resource_type = 2, .needed_gems = 8, .to_player_magic_lvl = -1, .to_enemy_tower = -9},
    { .pCardName = "Crumblestone", .slot = 47, .card_resource_type = 2, .needed_gems = 7, .to_player_tower = 5, .to_enemy_bricks = -6},
    { .pCardName = "Sapphire", .slot = 48, .card_resource_type = 2, .needed_gems = 10, .to_player_tower = 11},
    { .pCardName = "Discord", .slot = 49, .card_resource_type = 2, .needed_gems = 5, .to_pl_enm_magic_lvl = -1, .to_pl_enm_buildings = -7},
    { .pCardName = "Fire Ruby", .slot = 50, .card_resource_type = 2, .needed_gems = 13, .to_player_tower = 6, .to_enemy_tower = -4},
    { .pCardName = "Quarry's Help", .slot = 51, .card_resource_type = 2, .needed_gems = 4, .to_player_bricks = -10, .to_player_tower = 7},
    { .pCardName = "Crystal Shield", .slot = 52, .card_resource_type = 2, .needed_gems = 12, .to_player_wall = 3, .to_player_tower = 8},
    { .pCardName = "Empathy Gem", .slot = 53, .card_resource_type = 2, .needed_gems = 14, .to_player_zoo_lvl = 1, .to_player_tower = 8},
    { .pCardName = "Diamond", .slot = 54, .card_resource_type = 2, .needed_gems = 16, .to_player_tower = 15},
    { .pCardName = "Sanctuary", .slot = 55, .card_resource_type = 2, .needed_gems = 15, .to_player_beasts = 5, .to_player_wall = 5, .to_player_tower = 10},
    { .pCardName = "Lava Jewel", .slot = 56, .card_resource_type = 2, .needed_gems = 17, .to_player_tower = 12, .to_enemy_buildings = -6},
    { .pCardName = "Dragon's Eye", .slot = 57, .card_resource_type = 2, .needed_gems = 21, .to_player_tower = 20},
    { .pCardName = "Mad Cow Disease", .slot = 60, .card_resource_type = 3, .to_pl_enm_beasts = -6},
    { .pCardName = "Faerie", .slot = 61, .card_resource_type = 3, .needed_beasts = 1, .field_30 = 1, .to_enemy_buildings = -2},
    { .pCardName = "Moody Goblins", .slot = 62, .card_resource_type = 3, .needed_beasts = 1, .to_player_gems = -3, .to_enemy_buildings = -4},
    { .pCardName = "Husbandry", .slot = 63, .card_resource_type = 3, .needed_beasts = 3, .to_player_zoo_lvl = 1},
    { .pCardName = "Elven Scout", .slot = 64, .card_resource_type = 3, .needed_beasts = 2, .field_30 = 1, .draw_extra_card_count = 1},
    { .pCardName = "Goblin Mob", .slot = 65, .card_resource_type = 3, .needed_beasts = 3, .to_player_buildings = -3, .to_enemy_buildings = -6},
    { .pCardName = "Goblin Archers", .slot = 66, .card_resource_type = 3, .needed_beasts = 4, .to_player_buildings = -1, .to_enemy_tower = -3},
    { .pCardName = "Shadow Faerie", .slot = 67, .card_resource_type = 3, .needed_beasts = 6, .field_30 = 1, .to_enemy_tower = -2},
    { .pCardName = "Orc", .slot = 68, .card_resource_type = 3, .needed_beasts = 3, .to_enemy_buildings = -5},
    { .pCardName = "Dwarves", .slot = 69, .card_resource_type = 3, .needed_beasts = 5, .to_player_wall = 3, .to_enemy_buildings = -4},
    { .pCardName = "Little Snakes", .slot = 70, .card_resource_type = 3, .needed_beasts = 6, .to_enemy_tower = -4},
    { .pCardName = "Troll Keepers", .slot = 71, .card_resource_type = 3, .needed_beasts = 7, .to_player_zoo_lvl = 2},
    { .pCardName = "Tower Gremlins", .slot = 72, .card_resource_type = 3, .needed_beasts = 8, .to_player_wall = 4, .to_player_tower = 2, .to_enemy_buildings = -2},
    { .pCardName = "Full Moon", .slot = 73, .card_resource_type = 3, .to_player_beasts = 3, .to_pl_enm_zoo_lvl = 1},
    { .pCardName = "Slasher", .slot = 74, .card_resource_type = 3, .needed_beasts = 5, .to_enemy_buildings = -6},
    { .pCardName = "Ogre", .slot = 75, .card_resource_type = 3, .needed_beasts = 6, .to_enemy_buildings = -7},
    { .pCardName = "Rabid Sheep", .slot = 76, .card_resource_type = 3, .needed_beasts = 6, .to_enemy_beasts = -3, .to_enemy_buildings = -6},
    { .pCardName = "Imp", .slot = 77, .card_resource_type = 3, .needed_beasts = 5, .to_enemy_buildings = -6, .to_pl_enm_bricks = -5, .to_pl_enm_gems = -5, .to_pl_enm_beasts = -5},
    { .pCardName = "Spizzer", .slot = 78, .card_resource_type = 3, .needed_beasts = 8, .compare_param = ArcomageCompareParam::ENEMY_HAS_NO_WALL, .to_enemy_buildings = -10, .to_enemy_buildings2 = -6},
    { .pCardName = "Werewolf", .slot = 79, .card_resource_type = 3, .needed_beasts = 9, .to_enemy_buildings = -9},
    { .pCardName = "Corrosion Cloud", .slot = 80, .card_resource_type = 3, .needed_beasts = 11, .compare_param = ArcomageCompareParam::ENEMY_HAS_WALL, .to_enemy_buildings = -10, .to_enemy_buildings2 = -7},
    { .pCardName = "Unicorn", .slot = 81, .card_resource_type = 3, .needed_beasts = 9, .compare_param = ArcomageCompareParam::GREATER_MAGIC, .to_enemy_buildings = -12, .to_enemy_buildings2 = -8},
    { .pCardName = "Elven Archers", .slot = 82, .card_resource_type = 3, .needed_beasts = 10, .compare_param = ArcomageCompareParam::GREATER_WALL, .to_enemy_tower = -6, .to_enemy_buildings2 = -6},
    { .pCardName = "Succubus", .slot = 83, .card_resource_type = 3, .needed_beasts = 14, .to_enemy_beasts = -8, .to_enemy_tower = -5},
    { .pCardName = "Rock Stompers", .slot = 84, .card_resource_type = 3, .needed_beasts = 11, .to_enemy_quarry_lvl = -1, .to_enemy_buildings = -8},
    { .pCardName = "Thief", .slot = 85, .card_resource_type = 3, .needed_beasts = 12, .to_player_bricks = 3, .to_player_gems = 5, .to_enemy_bricks = -5, .to_enemy_gems = -10},
    { .pCardName = "Stone Giant", .slot = 86, .card_resource_type = 3, .needed_beasts = 15, .to_player_wall = 4, .to_enemy_buildings = -10},
    { .pCardName = "Vampire", .slot = 87, .card_resource_type = 3, .needed_beasts = 17, .to_enemy_zoo_lvl = -1, .to_enemy_beasts = -5, .to_enemy_buildings = -10},
    { .pCardName = "Dragon", .slot = 88, .card_resource_type = 3, .needed_beasts = 25, .to_enemy_zoo_lvl = -1, .to_enemy_gems = -10, .to_enemy_buildings = -20},
    { .pCardName = "Forced Labor", .slot = 28, .card_resource_type = 1, .needed_bricks = 7, .to_player_beasts = -5, .to_player_wall = 9},
    { .pCardName = "Crystallize", .slot = 58, .card_resource_type = 2, .needed_gems = 8, .to_player_wall = -6, .to_player_tower = 11}
};
