--- Default debug menu command buttons.
--- To add or reorder commands, just edit this list — no config renumbering needed.
--- User-defined extra commands can still be added via [cheat_commands] in openenroth.ini.
return {
    "config toggle town_portal | Town Portal",
    "config toggle wizard_eye | Wizard Eye",
    "config toggle all_magic | All Magic",
    "config toggle terrain | Terrain",
    "config toggle lightmap_decals | Lightmap Decals",
    "config toggle turbo_speed | Turbo Speed",
    "config toggle no_actors | No Actors",
    "config toggle no_damage | No Damage",
    "config toggle fog | Toggle Fog",
    "config toggle snow | Toggle Snow",
    "config toggle seasons_change | Toggle Seasons",
    "config toggle show_fps | Show FPS",
    "config toggle show_picked_face | Picked Face",
    "config toggle portal_outlines | Portal Outlines",
    "config toggle actor_collision | Actor Collision",
    "gold add 10000 | Add 10k Gold",
    "gold set 0 | Remove all Gold",
    "food add 20 | Add 20 Food",
    "food set 0 | Remove all Food",
    "xp party 20000 | Give 20k xp",
    "sp add 20 | Add 20 Skill points",
    "skills learn_all | Learn all Skills",
    "skills grandmaster_all | GM All Skills",
    "alignment cycle | Cycle Alignment",
    "class lich | Become Lich",
    "condition set Dead | Become Dead",
    "condition set Eradicated | Become Eradicated",
    "inventory addrandom | Add Random Item",
    "inventory addrandomspecial | Add Special Item",
    "reload_shaders | Reload Shaders",
    "hp full_heal | Full Heal",
}
