--- @meta

--- What one running event handler executes its commands in.
--- @class EvtScriptContext
--- @field execute fun(self: EvtScriptContext, name: string, args: table, player: integer|string): boolean?, string
--- @field isMapExitTriggered fun(self: EvtScriptContext): boolean

--- The Lua script of an evt file, in one piece for each event.
--- @class EvtDecompiledScript
--- @field header string
--- @field events { id: integer, code: string }[]

--- How a timer fires.
--- @class EvtTimerOptions
--- @field period number In ticks.
--- @field start number? Time of day in ticks that a daily timer fires at.
--- @field isRefill boolean
--- @field isGlobal boolean Whether the timer is kept when the party leaves the map.
--- @field countsFromNow boolean Whether the first alarm is counted from now, not from the last visit to the map.

--- @class EvtBindings
--- @field newContext fun(eventId: integer, targetPid: integer, canShowMessages: boolean): EvtScriptContext
--- @field defaultPlayer fun(): integer
--- @field commands fun(): string[]
--- @field constants fun(): table<string, table<string, number>>
--- @field removeEvent fun(isGlobal: boolean, eventId: integer)
--- @field clearEvents fun(isGlobal: boolean)
--- @field eventCount fun(isGlobal: boolean): integer
--- @field str fun(index: integer): string?
--- @field setStr fun(index: integer, value: string)
--- @field houseName fun(houseId: integer): string?
--- @field random fun(hi: integer): integer
--- @field time fun(): number
--- @field checkTimer fun(period: number, start: number?, isRefill: boolean)
--- @field addTimer fun(options: EvtTimerOptions, callback: fun(): boolean): integer
--- @field removeTimer fun(handle: integer)
--- @field mapScripts fun(mapName: string): string[]
--- @field globalScripts fun(): string[]
--- @field loadScript fun(path: string, environment: table): function?, string?
--- @field loadString fun(code: string, chunkName: string, environment: table): function?, string?
--- @field decompile fun(name: string): EvtDecompiledScript
--- @field isDecompilingEvents fun(): boolean
--- @field questBit fun(bit: integer): boolean
--- @field setQuestBit fun(bit: integer, value: boolean)
--- @field mouseItem fun(): integer
