#pragma once

#include <string>
#include <vector>

#include "Utility/Segment.h"

enum class InputAction {
    INPUT_ACTION_MOVE_FORWARD = 0,
    INPUT_ACTION_MOVE_BACKWARDS,
    INPUT_ACTION_TURN_LEFT,
    INPUT_ACTION_TURN_RIGHT,
    INPUT_ACTION_YELL,
    INPUT_ACTION_JUMP,
    INPUT_ACTION_TOGGLE_TURN_BASED,
    INPUT_ACTION_QUICK_CAST,
    INPUT_ACTION_ATTACK,
    INPUT_ACTION_INTERACT,
    INPUT_ACTION_OPEN_SPELLBOOK,
    INPUT_ACTION_PASS,
    INPUT_ACTION_NEXT_CHAR,
    INPUT_ACTION_OPEN_QUESTS,
    INPUT_ACTION_OPEN_QUICK_REFERENCE,
    INPUT_ACTION_REST,
    INPUT_ACTION_OPEN_CALENDAR,
    INPUT_ACTION_OPEN_AUTONOTES,
    INPUT_ACTION_OPEN_MAP,
    INPUT_ACTION_TOGGLE_ALWAYS_RUN,
    INPUT_ACTION_LOOK_UP,
    INPUT_ACTION_LOOK_DOWN,
    INPUT_ACTION_CENTER_VIEW,
    INPUT_ACTION_ZOOM_IN,
    INPUT_ACTION_ZOOM_OUT,
    INPUT_ACTION_FLY_UP,
    INPUT_ACTION_FLY_DOWN,
    INPUT_ACTION_FLY_LAND,

    INPUT_ACTION_STRAFE_LEFT,
    INPUT_ACTION_STRAFE_RIGHT,
    INPUT_ACTION_QUICK_SAVE,
    INPUT_ACTION_QUICK_LOAD,
    INPUT_ACTION_OPEN_HISTORY,
    INPUT_ACTION_OPEN_STATS,
    INPUT_ACTION_OPEN_SKILLS,
    INPUT_ACTION_OPEN_INVENTORY,
    INPUT_ACTION_OPEN_AWARDS,
    INPUT_ACTION_NEW_GAME,
    INPUT_ACTION_SAVE_GAME,
    INPUT_ACTION_LOAD_GAME,
    INPUT_ACTION_EXIT_GAME,
    INPUT_ACTION_BACK_TO_GAME,
    INPUT_ACTION_OPEN_CONTROLS,
    INPUT_ACTION_OPEN_OPTIONS,
    INPUT_ACTION_SHOW_CREDITS,
    INPUT_ACTION_PARTY_CREATION_CLEAR,
    INPUT_ACTION_PARTY_CREATION_DONE,
    INPUT_ACTION_PARTY_CREATION_DEC,
    INPUT_ACTION_PARTY_CREATION_INC,
    INPUT_ACTION_TRANSITION_YES,
    INPUT_ACTION_TRANSITION_NO,
    INPUT_ACTION_REST_HEAL,
    INPUT_ACTION_REST_WAIT_TILL_DAWN,
    INPUT_ACTION_REST_WAIT_1_HOUR,
    INPUT_ACTION_REST_WAIT_5_MINUTES,
    INPUT_ACTION_TAKE_SCREENSHOT,
    INPUT_ACTION_OPEN_CONSOLE,
    INPUT_ACTION_SELECT_CHAR_1,
    INPUT_ACTION_SELECT_CHAR_2,
    INPUT_ACTION_SELECT_CHAR_3,
    INPUT_ACTION_SELECT_CHAR_4,
    INPUT_ACTION_SELECT_NPC_1,
    INPUT_ACTION_SELECT_NPC_2,
    INPUT_ACTION_DIALOG_UP,
    INPUT_ACTION_DIALOG_DOWN,
    INPUT_ACTION_DIALOG_LEFT,
    INPUT_ACTION_DIALOG_RIGHT,
    INPUT_ACTION_DIALOG_PRESS,
    INPUT_ACTION_ESCAPE,
    INPUT_ACTION_TOGGLE_MOUSE_LOOK,
    INPUT_ACTION_TOGGLE_WINDOW_MODE,

    INPUT_ACTION_INVALID = -1,

    INPUT_ACTION_FIRST_VALID = INPUT_ACTION_MOVE_FORWARD,
    INPUT_ACTION_LAST_VALID = INPUT_ACTION_TOGGLE_WINDOW_MODE,

    INPUT_ACTION_FIRST_CONFIGURABLE = INPUT_ACTION_MOVE_FORWARD, // Configurable from the game options menu.
    INPUT_ACTION_LAST_CONFIGURABLE = INPUT_ACTION_FLY_LAND,
};
using enum InputAction;

inline Segment<InputAction> allInputActions() {
    return {INPUT_ACTION_FIRST_VALID, INPUT_ACTION_LAST_VALID};
}

inline Segment<InputAction> allConfigurableInputActions() {
    return {INPUT_ACTION_FIRST_CONFIGURABLE, INPUT_ACTION_LAST_CONFIGURABLE};
}

std::string GetDisplayName(InputAction action);
